"use client";
import { useEffect, useState } from "react";

type Binding = { tenant_id:string; username:string; state:string; job_id:number; allocation_generation:number; credential_profile:string; profile_instance_id:string };
type EnrollmentIdentity = { reservation_id:string;nonce:string;job_id:number;allocation_binding_id:string;allocation_generation:number;credential_profile:string;profile_instance_id:string;expires_at_utc:string };
const b64=(bytes:ArrayBuffer|ArrayBufferView)=>{const view=bytes instanceof ArrayBuffer?new Uint8Array(bytes):new Uint8Array(bytes.buffer,bytes.byteOffset,bytes.byteLength);return btoa(String.fromCharCode(...view))};
const hex=(bytes:ArrayBuffer)=>[...new Uint8Array(bytes)].map((value)=>value.toString(16).padStart(2,"0")).join("");

export function TenantHpcEnrollment(){
 const [binding,setBinding]=useState<Binding|null>(null);const [message,setMessage]=useState("");
 const [reclaimConfirmed,setReclaimConfirmed]=useState(false);const [lifecycleBusy,setLifecycleBusy]=useState(false);
 const [job,setJob]=useState("");const [allocation,setAllocation]=useState("");const [role,setRole]=useState("");const [proxyUser,setProxyUser]=useState("");const [proxyPassword,setProxyPassword]=useState("");const [hpcPassword,setHpcPassword]=useState("");
 const refresh=async()=>{const response=await fetch("/api/hpc/byoa/binding",{cache:"no-store"});const data=await response.json();setBinding(data.binding??null)};
 useEffect(()=>{void refresh()},[]);
 const enroll=async()=>{setMessage("正在加密 enrollment envelope…");try{
  const csrf=sessionStorage.getItem("evomind.local.csrf.v1");if(!csrf)throw new Error("csrf_missing");const bindingResponse=await fetch("/api/hpc/byoa/binding",{cache:"no-store"});await bindingResponse.json();const sessionResponse=await fetch("/api/session/status",{cache:"no-store"});const sessionData=await sessionResponse.json();
  const keyResponse=await fetch("/api/hpc/byoa/public-key",{cache:"no-store"});const key=await keyResponse.json();if(!keyResponse.ok)throw new Error(key.code);
  const intentResponse=await fetch("/api/hpc/byoa/enrollment-identity",{method:"POST",headers:{"Content-Type":"application/json","x-evomind-csrf":csrf},body:JSON.stringify({job_id:Number(job),allocation_binding_id:allocation})});const intent=await intentResponse.json() as EnrollmentIdentity&{code?:string};if(!intentResponse.ok)throw new Error(intent.code??"enrollment_identity_rejected");
  const tenant=String(sessionData.tenant_id);const owner=String(sessionData.username);const {nonce,profile_instance_id:profileInstance,allocation_generation:generation}=intent;
  const source=`${tenant}|${owner}|${nonce}|${intent.job_id}|${generation}|${profileInstance}`;const bindingHash=hex(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(source)));
  const payload={schema:"evomind.tenant_enrollment_secret.v1",binding_sha256:bindingHash,hpc_role_account:role,proxy_user:proxyUser,proxy_password:proxyPassword,hpc_password:hpcPassword};
  const publicKey=await crypto.subtle.importKey("jwk",key.rsa_jwk,{name:"RSA-OAEP",hash:"SHA-256"},false,["encrypt"]);const aesKey=await crypto.subtle.generateKey({name:"AES-GCM",length:256},true,["encrypt"]);const rawKey=await crypto.subtle.exportKey("raw",aesKey);const wrappedKey=await crypto.subtle.encrypt({name:"RSA-OAEP"},publicKey,rawKey);const iv=crypto.getRandomValues(new Uint8Array(12));const aad=new TextEncoder().encode(`${tenant}|${owner}|${nonce}|${intent.job_id}|${generation}|${profileInstance}|${key.key_id}`);const encrypted=await crypto.subtle.encrypt({name:"AES-GCM",iv,additionalData:aad,tagLength:128},aesKey,new TextEncoder().encode(JSON.stringify(payload)));const encryptedBytes=new Uint8Array(encrypted);const ciphertext=encryptedBytes.slice(0,-16);const tag=encryptedBytes.slice(-16);
  const response=await fetch("/api/hpc/byoa/enrollment-envelope",{method:"POST",headers:{"Content-Type":"application/json","x-evomind-csrf":csrf},body:JSON.stringify({reservation_id:intent.reservation_id,job_id:intent.job_id,allocation_binding_id:intent.allocation_binding_id,encrypted_envelope:{schema:"evomind.hybrid_tenant_envelope.v1",algorithm:"RSA-OAEP-256+A256GCM",key_id:key.key_id,wrapped_key:b64(wrappedKey),iv:b64(iv),ciphertext:b64(ciphertext),tag:b64(tag)}})});const result=await response.json();if(!response.ok)throw new Error(result.code);setMessage(`Generation ${generation} 的加密 envelope 已接收，服务账户将从当前 allocation 的 5/5 只读探测中绑定 Host/GPU 身份。`);setProxyPassword("");setHpcPassword("");await refresh();
 }catch(error){setMessage(error instanceof Error?error.message:"enrollment_failed");setProxyPassword("");setHpcPassword("");}};
 const replaceFailedProvisioning=async()=>{if(!binding||binding.state!=="provisioning"||lifecycleBusy)return;setLifecycleBusy(true);setMessage("正在废弃未激活的失败 enrollment…");try{const csrf=sessionStorage.getItem("evomind.local.csrf.v1");if(!csrf)throw new Error("csrf_missing");const response=await fetch("/api/hpc/byoa/binding",{method:"POST",headers:{"Content-Type":"application/json","x-evomind-csrf":csrf},body:JSON.stringify({action:"replace_failed_provisioning"})});const result=await response.json();if(!response.ok||!result.ok||result.replacement_allowed!==true)throw new Error(result.code??"failed_provisioning_replacement_rejected");setMessage(`Generation ${binding.allocation_generation} 的失败登记已废弃；未发现激活回执或身份样本，可安全重新登记。`);setProxyPassword("");setHpcPassword("");await refresh()}catch(error){setMessage(error instanceof Error?error.message:"failed_provisioning_replacement_failed")}finally{setLifecycleBusy(false)}};
 const retire=async()=>{if(!binding||!reclaimConfirmed||lifecycleBusy)return;setLifecycleBusy(true);setMessage("正在退役旧 allocation 与独立 DPAPI profile…");try{const csrf=sessionStorage.getItem("evomind.local.csrf.v1");if(!csrf)throw new Error("csrf_missing");const response=await fetch("/api/hpc/byoa/binding",{method:"POST",headers:{"Content-Type":"application/json","x-evomind-csrf":csrf},body:JSON.stringify({action:"retire",administrator_reclaim_confirmed:true,reason:"allocation_reclaimed_by_administrator"})});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.code??"tenant_profile_retirement_rejected");setMessage(`Generation ${binding.allocation_generation} 已退役；旧 profile tombstone 已验证，可登记新的 allocation。`);setReclaimConfirmed(false);setProxyPassword("");setHpcPassword("");await refresh()}catch(error){setMessage(error instanceof Error?error.message:"tenant_profile_retirement_failed")}finally{setLifecycleBusy(false)}};
 return <section className="rounded-xl border border-edge bg-surface p-4"><h3 className="text-sm font-semibold text-ink">我的 AIMSLAB allocation</h3><p className="mt-1 text-xs text-ink-muted">每个用户只绑定自己的 allocation 和独立 DPAPI profile，不共享其他用户的 job。无 active binding 时上传和训练保持关闭。</p><div className="mt-3 text-xs">状态：<strong>{binding?.state??"未绑定"}</strong>{binding?<span className="ml-2 font-mono">{binding.credential_profile}</span>:null}</div>
 <div className="mt-3 grid gap-2 md:grid-cols-3">{[[job,setJob,"Job ID"],[allocation,setAllocation,"Allocation binding ID"],[role,setRole,"HPC role account"],[proxyUser,setProxyUser,"Proxy user"]] .map(([value,setter,label])=><input key={String(label)} value={value as string} onChange={(event)=>(setter as (v:string)=>void)(event.target.value)} placeholder={String(label)} className="h-10 rounded border border-edge bg-surface px-3 text-xs"/>)}<input type="password" autoComplete="new-password" value={proxyPassword} onChange={(event)=>setProxyPassword(event.target.value)} placeholder="Proxy password" className="h-10 rounded border border-edge bg-surface px-3 text-xs"/><input type="password" autoComplete="new-password" value={hpcPassword} onChange={(event)=>setHpcPassword(event.target.value)} placeholder="HPC password" className="h-10 rounded border border-edge bg-surface px-3 text-xs"/></div><p className="mt-2 text-[11px] text-ink-muted">Generation、nonce 和 profile UUID 由服务器在提交时签发，只读且不可复用。</p>
 <div className="mt-3 flex flex-wrap items-center gap-3"><button type="button" disabled={Boolean(binding&&binding.state!=="retired")||lifecycleBusy} onClick={()=>void enroll()} className="rounded-lg bg-accent px-4 py-2 text-xs font-semibold text-accent-foreground disabled:cursor-not-allowed disabled:opacity-50">用服务器公钥加密并提交</button>{binding?.state==="provisioning"?<button type="button" disabled={lifecycleBusy} onClick={()=>void replaceFailedProvisioning()} className="rounded-lg border border-danger-border px-3 py-2 text-xs font-semibold text-danger-text disabled:cursor-not-allowed disabled:opacity-50">{lifecycleBusy?"正在检查并废弃…":"废弃失败登记并重新填写"}</button>:binding&&binding.state!=="retired"?<><label className="flex items-center gap-2 text-[11px] text-ink-muted"><input type="checkbox" checked={reclaimConfirmed} onChange={(event)=>setReclaimConfirmed(event.target.checked)} />我确认当前 allocation 已被管理员回收或替换</label><button type="button" disabled={!reclaimConfirmed||lifecycleBusy} onClick={()=>void retire()} className="rounded-lg border border-danger-border px-3 py-2 text-xs font-semibold text-danger-text disabled:cursor-not-allowed disabled:opacity-50">{lifecycleBusy?"正在退役…":"退役当前 allocation"}</button></>:null}</div>{message?<p role="status" className="mt-2 text-xs text-ink-secondary">{message}</p>:null}</section>;
}

