"""Purpose-bound CurrentUser DPAPI blobs, never plaintext credential files."""
from __future__ import annotations

import ctypes
from ctypes import wintypes
import hashlib
import os
from pathlib import Path
import subprocess


def private_directory(path: Path) -> None:
    if os.name != 'nt':
        raise ValueError('model_profiles_require_windows_dpapi')
    for parent in (path, *path.parents):
        if parent.exists() and getattr(parent.lstat(), 'st_file_attributes', 0) & 1024:
            raise ValueError('credential_reparse_path_rejected')
    # Check existing ACLs; never silently broaden or repair an existing folder.
    script = r'''
$ErrorActionPreference='Stop'
$path=$env:EVOMIND_PRIVATE_PROFILE_DIRECTORY
$sid=[Security.Principal.WindowsIdentity]::GetCurrent().User
$system=[Security.Principal.SecurityIdentifier]::new('S-1-5-18')
if(-not [IO.Directory]::Exists($path)){
 [IO.Directory]::CreateDirectory($path)|Out-Null
 $acl=[Security.AccessControl.DirectorySecurity]::new()
 # Set only the DACL. Reassigning the owner unnecessarily needs WRITE_OWNER
 # on some volumes even though the process may set a private DACL there.
 $acl.SetAccessRuleProtection($true,$false)
 foreach($identity in @($sid,$system)){
  $acl.AddAccessRule([Security.AccessControl.FileSystemAccessRule]::new($identity,'FullControl','ContainerInherit,ObjectInherit','None','Allow'))
 }
 [IO.Directory]::SetAccessControl($path,$acl)
}
$acl=[IO.Directory]::GetAccessControl($path)
if(-not $acl.AreAccessRulesProtected){throw 'unprotected_directory'}
foreach($rule in $acl.Access){
 if($rule.AccessControlType -eq 'Allow' -and $rule.IdentityReference.Translate([Security.Principal.SecurityIdentifier]).Value -notin @($sid.Value,$system.Value)){throw 'broad_directory_acl'}
}
'''
    result = subprocess.run(['powershell.exe', '-NoProfile', '-NonInteractive', '-Command', script],
        env={**os.environ, 'EVOMIND_PRIVATE_PROFILE_DIRECTORY': str(path)},
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=15, creationflags=subprocess.CREATE_NO_WINDOW)
    if result.returncode:
        raise ValueError('credential_directory_acl_failed')


def crypt(payload: bytes, purpose: str, *, decrypt=False) -> bytes:
    if os.name != 'nt' or len(payload) > 32768:
        raise ValueError('credential_protection_unavailable')

    class Blob(ctypes.Structure):
        _fields_ = [('length', wintypes.DWORD), ('data', ctypes.POINTER(ctypes.c_byte))]

    def blob(value):
        buffer = ctypes.create_string_buffer(value)
        return Blob(len(value), ctypes.cast(buffer, ctypes.POINTER(ctypes.c_byte))), buffer

    source, source_buffer = blob(payload)
    entropy, entropy_buffer = blob(hashlib.sha256(('evomind.personal-model.v1:' + purpose).encode()).digest())
    result = Blob()
    api = ctypes.WinDLL('crypt32', use_last_error=True)
    kernel = ctypes.WinDLL('kernel32', use_last_error=True)
    fn = api.CryptUnprotectData if decrypt else api.CryptProtectData
    fn.argtypes = [ctypes.POINTER(Blob), ctypes.c_void_p, ctypes.POINTER(Blob), ctypes.c_void_p, ctypes.c_void_p, wintypes.DWORD, ctypes.POINTER(Blob)]
    fn.restype = wintypes.BOOL
    kernel.LocalFree.argtypes = [ctypes.c_void_p]
    kernel.LocalFree.restype = ctypes.c_void_p
    if not fn(ctypes.byref(source), None, ctypes.byref(entropy), None, None, 1, ctypes.byref(result)):
        raise ValueError('credential_protection_failed')
    try:
        return ctypes.string_at(result.data, result.length)
    finally:
        kernel.LocalFree(result.data)


class ProfileSecrets:
    def __init__(self, root: Path):
        self.root = root / 'private-model-profiles'

    def path(self, tenant, owner, profile_id, version):
        # All path components are generated by the server, not user names.
        purpose = '\0'.join((tenant, owner, profile_id, str(version)))
        digest = hashlib.sha256(purpose.encode()).hexdigest()
        private_directory(self.root)
        path = self.root / (digest + '.dpapi')
        if path.exists() and getattr(path.lstat(), 'st_file_attributes', 0) & 1024:
            raise ValueError('credential_reparse_path_rejected')
        return path, purpose

    def save(self, tenant, owner, profile_id, version, secret):
        path, purpose = self.path(tenant, owner, profile_id, version)
        cipher = crypt(secret.encode(), purpose)
        # Create-new preserves every already-bound revision, including after a crash.
        if path.exists():
            if crypt(path.read_bytes(), purpose, decrypt=True).decode() != secret:
                raise ValueError('credential_revision_already_exists')
            return
        with path.open('xb') as handle:
            handle.write(cipher)
            handle.flush()
            os.fsync(handle.fileno())

    def load(self, tenant, owner, profile_id, version):
        path, purpose = self.path(tenant, owner, profile_id, version)
        return crypt(path.read_bytes(), purpose, decrypt=True).decode()
