import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
const root=new URL("../../",import.meta.url);
const ui=await readFile(new URL("components/workstation/TenantHpcEnrollment.tsx",root),"utf8");
const envelope=await readFile(new URL("app/api/hpc/byoa/enrollment-envelope/route.ts",root),"utf8");
const identity=await readFile(new URL("app/api/hpc/byoa/enrollment-identity/route.ts",root),"utf8");
const binding=await readFile(new URL("app/api/hpc/byoa/binding/route.ts",root),"utf8");
const tenantByoa=await readFile(new URL("lib/server/tenant-byoa.ts",root),"utf8");
test("browser uses server key hybrid encryption CSRF and server rejects plaintext secret fields",()=>{assert.match(ui,/RSA-OAEP-256\+A256GCM/);assert.match(ui,/AES-GCM/);assert.match(ui,/additionalData:aad/);assert.match(ui,/evomind\.local\.csrf\.v1/);assert.match(ui,/x-evomind-csrf/);assert.match(envelope,/plaintext_secret_rejected/);assert.match(envelope,/keyRecord\.key_id !== envelope\.key_id/)});
test("server issues and consumes enrollment identity instead of trusting browser generation uuid or nonce",()=>{assert.match(ui,/\/api\/hpc\/byoa\/enrollment-identity/);assert.match(identity,/issueTenantEnrollmentIdentity/);assert.match(identity,/authoritative_now_ms/);assert.match(identity,/server_issued_identity_required/);assert.match(envelope,/consumeTenantEnrollmentIdentity/);assert.match(envelope,/reservation_id/);assert.match(envelope,/authoritative_now_ms:authoritativeNow/);assert.match(envelope,/server_issued_identity_required/);assert.doesNotMatch(ui,/crypto\.randomUUID\(\)/);assert.doesNotMatch(ui,/setGeneration|setInstance|Profile instance UUID/);assert.doesNotMatch(envelope,/createProvisioningBinding/);});
test("provisioning identity comes from the strict five-sample activation probe",()=>{assert.doesNotMatch(ui,/Expected Host UUID|Expected GPU UUID|Container binding SHA-256/);assert.doesNotMatch(envelope,/body\.expected_host_uuid|body\.expected_gpu_uuid|body\.container_binding_sha256/);assert.match(tenantByoa,/expected_host_uuid: ""/);assert.match(tenantByoa,/expected_gpu_uuid: ""/);assert.match(tenantByoa,/container_binding_sha256: ""/)});
test("activation requires a generation scoped persisted receipt and reclaim is explicit local-first and retryable",()=>{assert.match(binding,/activation-receipts/);assert.match(binding,/current\.allocation_generation/);assert.match(binding,/administrator_reclaim_confirmed/);assert.match(binding,/transitionTenantHpcProfile[\s\S]*freezeOrRetireBinding/);assert.match(ui,/退役当前 allocation/);assert.match(ui,/x-evomind-csrf/)});
test("failed provisioning can be replaced only before any receipt or identity evidence exists",()=>{assert.match(binding,/replace_failed_provisioning/);assert.match(binding,/retryable_activation_failure/);assert.match(binding,/failed_provisioning_receipt_exists/);assert.match(binding,/failed_provisioning_identity_evidence_exists/);assert.match(binding,/transitionTenantHpcProfile[\s\S]*failed_provisioning_replaced[\s\S]*freezeOrRetireBinding/);assert.match(ui,/废弃失败登记并重新填写/);assert.match(ui,/replacement_allowed/)});
test("server uses a service-instance system-QPC anchor without request helpers",()=>{assert.match(envelope,/async function managedUtcNowMs/);assert.match(envelope,/EVOMIND_SERVICE_CLOCK_ANCHOR_PATH/);assert.match(envelope,/EVOMIND_SERVICE_INSTANCE_ID/);assert.match(envelope,/EVOMIND_BOOT_ID/);assert.match(envelope,/EVOMIND_CLOCK_QPC_TIMESTAMP/);assert.match(envelope,/EVOMIND_CLOCK_QPC_FREQUENCY/);assert.match(envelope,/process\.hrtime\.bigint\(\)/);assert.match(envelope,/time_source:clock\.source/);assert.doesNotMatch(envelope,/process\.platform\s*!==\s*["']win32["']|execFile|WindowsPowerShell|child_process/);assert.match(envelope,/serverExpiresAt = issuedAt \+ 10 \* 60_000/)});
test("envelope publication stages before reservation commit and journals post-commit recovery",()=>{assert.match(envelope,/receipt\.staged\.json/);assert.match(envelope,/consumeTenantEnrollmentIdentity[\s\S]*async\(reservation,prospectiveBinding\)/);assert.match(envelope,/fs\.link\(stagedReceipt,receipt\)/);assert.match(envelope,/uncommitted_enrollment_publish_marker_rejected/);assert.match(envelope,/committed_pending_watcher_recovery/);assert.match(envelope,/if\(!consumedExists\)/)});

