param(
  [string]$CandidateTools='',
  [string]$CandidateOverlay='',
  [string]$Release='v15r22-r13',
  [string]$BuildId='overlay-super-agent-byoa-v15r22-r9-92abb43074a5',
  [string]$BaseToolsSha='17b41a1c8ba0547309b510cb8aa8d0249714d1201631b0ab3db801458ddc6ab4',
  [switch]$AllowUnchangedTools,
  [string]$SourceManifestPath='D:\AI-Outputs\EvoMind-Cloud-Deploy\artifacts\super-agent-v15r22-r13-hpc-executor-overlay-source-manifest-20260817.json',
  [string]$ZipPath='D:\AI-Outputs\EvoMind-Cloud-Deploy\artifacts\super-agent-hpc-executor-overlay-hotfix-v15r22-r13-20260817.zip',
  [string]$TestResultPath='D:\AI-Outputs\EvoMind-Cloud-Deploy\artifacts\super-agent-hpc-executor-overlay-hotfix-v15r22-r13-test-results-20260817.json'
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$projectRoot=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$CandidateTools=if($CandidateTools){[IO.Path]::GetFullPath($CandidateTools)}else{Join-Path $projectRoot 'src\evomind_runtime\tools.py'}
$CandidateOverlay=if($CandidateOverlay){[IO.Path]::GetFullPath($CandidateOverlay)}else{Join-Path $projectRoot 'src\evomind_runtime\hpc_runtime_overlay.py'}
$fixture=Join-Path $projectRoot 'tests\test_hpc_execute_solution_workspace.py'
$buildId=$BuildId;$release=$Release
$baseToolsSha=$BaseToolsSha;$sourceManifest=[IO.Path]::GetFullPath($SourceManifestPath);$zip=[IO.Path]::GetFullPath($ZipPath);$testResult=[IO.Path]::GetFullPath($TestResultPath)
$testFiles=@('tests/test_hpc_execute_solution_workspace.py','tests/test_aibuild_hpc_workflow.py','tests/test_evomind_runtime.py','tests/test_assistant_run_service.py','tests/test_assistant_training.py','tests/test_hpc_only_training_policy.py','tests/test_hpc_runtime_contract.py')
function Sha([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Write-Utf8([string]$Path,[object]$Value){$parent=Split-Path -Parent $Path;if($parent){New-Item -ItemType Directory -Path $parent -Force|Out-Null};[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 12)+"`n"),[Text.UTF8Encoding]::new($false))}
function Assert-File([string]$Path){if(-not(Test-Path -LiteralPath $Path -PathType Leaf)){throw "R13_INPUT_MISSING:$Path"}}
function ZipFiles([string]$Root){@(Get-ChildItem -LiteralPath $Root -Recurse -File -Force|Where-Object{$_.FullName-notmatch'[\\/]__pycache__[\\/]'-and$_.Extension-notin@('.pyc','.pyo')}|Sort-Object FullName|ForEach-Object{[ordered]@{path=$_.FullName.Substring($Root.Length).TrimStart('\').Replace('\','/');bytes=[long]$_.Length;sha256=Sha $_.FullName}})}
foreach($path in @($CandidateTools,$CandidateOverlay,$fixture)){Assert-File $path};foreach($path in @($sourceManifest,$zip,$testResult)){if(Test-Path -LiteralPath $path){throw "R13_OUTPUT_EXISTS:$path"}}
if(-not$AllowUnchangedTools-and(Sha $CandidateTools)-eq$baseToolsSha){throw 'R13_TOOLS_CANDIDATE_DID_NOT_CHANGE'}
$stamp=[guid]::NewGuid().ToString('N');$ascii='D:\EV12';New-Item -ItemType Directory -Path $ascii -Force|Out-Null;$stage=Join-Path $ascii "r13-hpc-overlay-$stamp";$a=Join-Path $ascii "r13-hpc-overlay-a-$stamp";$b=Join-Path $ascii "r13-hpc-overlay-b-$stamp";foreach($path in @($stage,$a,$b)){if(Test-Path -LiteralPath $path){throw "R13_ASCII_STAGE_EXISTS:$path"}}
New-Item -ItemType Directory -Path (Join-Path $stage 'evomind_runtime') -Force|Out-Null;Copy-Item -LiteralPath $CandidateTools -Destination (Join-Path $stage 'evomind_runtime\tools.py');Copy-Item -LiteralPath $CandidateOverlay -Destination (Join-Path $stage 'evomind_runtime\hpc_runtime_overlay.py')
$files=@([ordered]@{path='evomind_runtime/tools.py';base_sha256=$baseToolsSha;sha256=Sha (Join-Path $stage 'evomind_runtime\tools.py');bytes=[long](Get-Item (Join-Path $stage 'evomind_runtime\tools.py')).Length},[ordered]@{path='evomind_runtime/hpc_runtime_overlay.py';base_sha256='absent_from_production_bundle';sha256=Sha (Join-Path $stage 'evomind_runtime\hpc_runtime_overlay.py');bytes=[long](Get-Item (Join-Path $stage 'evomind_runtime\hpc_runtime_overlay.py')).Length})
$source=[ordered]@{schema='evomind.super_agent_hpc_executor_overlay_source_set.v1';build_id=$buildId;release=$release;frozen=$true;file_count=2;files=$files;fixture=[ordered]@{path='tests/test_hpc_execute_solution_workspace.py';sha256=Sha $fixture;bytes=[long](Get-Item $fixture).Length};boundaries=[ordered]@{ascii_build_root=$ascii;production_read_only_during_build=$true;hpc_accessed=$false;gpu_touched=$false;training_started=$false;kaggle_submissions=0;secrets_included=$false}}
Write-Utf8 $sourceManifest $source;$sourceSha=Sha $sourceManifest
$manifest=[ordered]@{schema='evomind.super_agent_hpc_executor_overlay_hotfix.v1';build_id=$buildId;release=$release;source_manifest_sha256=$sourceSha;file_count=2;files=$files};Write-Utf8 (Join-Path $stage 'hpc-executor-overlay-hotfix-manifest.json') $manifest
Compress-Archive -Path (Join-Path $stage '*') -DestinationPath $zip -CompressionLevel Optimal;$zipSha=Sha $zip;Expand-Archive -LiteralPath $zip -DestinationPath $a;Expand-Archive -LiteralPath $zip -DestinationPath $b
$expected=@([ordered]@{path='hpc-executor-overlay-hotfix-manifest.json';bytes=[long](Get-Item (Join-Path $stage 'hpc-executor-overlay-hotfix-manifest.json')).Length;sha256=Sha (Join-Path $stage 'hpc-executor-overlay-hotfix-manifest.json')})+$files;$runs=@()
foreach($root in @($a,$b)){$actual=ZipFiles $root;if($actual.Count-ne3){throw "R13_FILESET_COUNT_REJECTED:$root"};foreach($entry in $expected){$row=@($actual|Where-Object{$_.path-eq$entry.path});if($row.Count-ne1-or$row[0].bytes-ne$entry.bytes-or$row[0].sha256-ne$entry.sha256){throw "R13_FILESET_HASH_REJECTED:$($entry.path)"}}
  $overlayRoot=Join-Path $root 'verification-overlay';$overlaySrc=Join-Path $overlayRoot 'src';Copy-Item -LiteralPath (Join-Path $projectRoot 'src') -Destination $overlaySrc -Recurse;Copy-Item -LiteralPath (Join-Path $root 'evomind_runtime\tools.py') -Destination (Join-Path $overlaySrc 'evomind_runtime\tools.py') -Force;Copy-Item -LiteralPath (Join-Path $root 'evomind_runtime\hpc_runtime_overlay.py') -Destination (Join-Path $overlaySrc 'evomind_runtime\hpc_runtime_overlay.py') -Force
  $old=[Environment]::GetEnvironmentVariable('PYTHONPATH','Process');try{$env:PYTHONPATH=$overlaySrc;$identity=& uv run python -c "import hashlib,json;import evomind_runtime.tools as t;import evomind_runtime.hpc_runtime_overlay as h;p=lambda x:hashlib.sha256(open(x,'rb').read()).hexdigest();print(json.dumps({'tools':p(t.__file__),'overlay':p(h.__file__),'tools_path':t.__file__,'overlay_path':h.__file__}))";if($LASTEXITCODE-ne0){throw "R13_IMPORT_FAILED:$root"};$id=$identity|Out-String|ConvertFrom-Json;if([string]$id.tools-ne[string]$files[0].sha256-or[string]$id.overlay-ne[string]$files[1].sha256){throw "R13_IMPORT_HASH_REJECTED:$root"};$compile=& uv run python -m py_compile (Join-Path $overlaySrc 'evomind_runtime\tools.py') (Join-Path $overlaySrc 'evomind_runtime\hpc_runtime_overlay.py') 2>&1;if($LASTEXITCODE-ne0){throw "R13_COMPILE_FAILED:$root"};$tests=& uv run pytest -q @testFiles 2>&1;if($LASTEXITCODE-ne0){throw "R13_TESTS_FAILED:$root`n$($tests|Out-String)"};$runs+=[ordered]@{extract_root=$root;overlay_src=$overlaySrc;identity=$id;compile='passed';tests='passed';test_files=$testFiles}}finally{if($null-eq$old){Remove-Item Env:PYTHONPATH -ErrorAction SilentlyContinue}else{[Environment]::SetEnvironmentVariable('PYTHONPATH',$old,'Process')}}}
$payload=[ordered]@{schema='evomind.super_agent_hpc_executor_overlay_hotfix_test_result.v1';status='passed';build_id=$buildId;release=$release;zip_path=$zip;zip_sha256=$zipSha;source_manifest_path=$sourceManifest;source_manifest_sha256=$sourceSha;independent_extract_runs=2;verification_runs=$runs;files=$files;boundaries=[ordered]@{hpc_accessed=$false;gpu_touched=$false;remote_commands=0;training_started=$false;kaggle_submissions=0;secrets_included=$false}};Write-Utf8 $testResult $payload;[ordered]@{status='passed';zip_path=$zip;zip_sha256=$zipSha;source_manifest_path=$sourceManifest;source_manifest_sha256=$sourceSha;test_result_path=$testResult;test_result_sha256=Sha $testResult}|ConvertTo-Json -Compress
