param(
  [Parameter(Mandatory)][ValidatePattern('^[a-f0-9]{32}$')][string]$TransactionId,
  [Parameter(Mandatory)][string]$RemoteRoot,
  [Parameter(Mandatory)][ValidatePattern('^[a-f0-9]{64}$')][string]$ApprovalSha256
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$root = 'C:\ProgramData\EvoMind'
$expectedRemote = [IO.Path]::GetFullPath("C:\SecureInput\r123-managed-hpc-rebind-runtime-$TransactionId")
if ([IO.Path]::GetFullPath($RemoteRoot) -cne $expectedRemote) { throw 'R123_REMOTE_ROOT_REJECTED' }
$inputRoot = Join-Path $expectedRemote 'envelope-expanded'
$approvalPath = Join-Path $inputRoot 'approval.json'
$archive = Join-Path $inputRoot 'runtime.zip'
$sourceManifestPath = Join-Path $inputRoot 'source-manifest.json'
$buildResultPath = Join-Path $inputRoot 'build-result.json'
$receiptPath = Join-Path $inputRoot 'test-receipt.json'
$stage = Join-Path $expectedRemote 'runtime-stage'
$resultPath = Join-Path $expectedRemote "transaction-$TransactionId-result.json"
$errorPath = Join-Path $expectedRemote "transaction-$TransactionId-error.json"
$action = 'C:\SecureInput\Invoke-ServiceAccountAction.ps1'
$seal = Join-Path $root 'bundle\scripts\Seal-Release.ps1'
$bundleRuntime = Join-Path $root 'bundle\runtime'
$target = Join-Path $bundleRuntime 'evomind_runtime'
$fixedRun = 'run_7b1efb878afb40f396db431e91f093a5'
$legacyGoalAllocation = 'G21'
$targetAllocation = 'G24'
$fixedTenant = 'tenant_ba0ef9d3767f2fb385b856e0'
$fixedJob = 93015
$fixedGeneration = 24
$fixedWebBuild = 'overlay-assistant-interaction-r122-1393046c9de7'
$baselineZipSha = 'f927d3538b6b1f1a02ed4fb57312d2663296e98baa56940660c321058440f4d2'
$baselineTreeSha = 'a9595ab4ed9a86786ca65f4456893d64741b449ec84cf8c9ddb42e9bf4110dc7'
$baselineManifestSha = 'd644dc05a01cc4fec0201716bbfdc7a108a7f412c9cc98edfe95ef7a3bac8da8'
$candidateTreeSha = '4bb0803db0e0fed319e45f4ac39152382fdcb762650cb2009d1fcd2b0e9d17fc'
$goalSpecSha = 'fbb9939dff28c355c2798bf32fce104845337064f42f9c280f2b6906cccf4036'
$goalBoardSha = '6b908173083889ac21f8afea52528b4b5e35d2ff862a880a6065d65b169f443c'
$manifestName = 'managed-hpc-identity-rebind-runtime-r123-manifest.json'
$changedFiles = @('evomind_runtime/assistant_runs.py','evomind_runtime/http_server.py','evomind_runtime/store.py')

function Sha([string]$Path){$stream=[IO.File]::OpenRead($Path);$hash=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($hash.ComputeHash($stream))).Replace('-','').ToLowerInvariant()}finally{$stream.Dispose();$hash.Dispose()}}
function SafeError([object]$Value){$text=[string]$Value;$text=$text-replace'(?i)(?:Bearer|Basic)\s+\S+','[credential redacted]';$text=$text-replace'(?i)\b(?:password|passwd|pwd|credential|token|secret|api[_ -]?key|authorization|bearer|密码|口令|凭据|账号|登录)\s*[:=]\s*\S+','[credential redacted]';$text=$text-replace'[\r\n]+','_';if($text.Length-gt500){$text=$text.Substring(0,500)};$text}
function WriteJson([string]$Path,[object]$Value){$tmp="$Path.$PID.tmp";[IO.File]::WriteAllText($tmp,(($Value|ConvertTo-Json -Depth 50)+"`n"),[Text.UTF8Encoding]::new($false));Move-Item -LiteralPath $tmp -Destination $Path -Force}
function ReadObj([string]$Path,[string]$Code){if(-not(Test-Path -LiteralPath $Path -PathType Leaf)){throw "$Code`:MISSING"};try{$v=Get-Content -LiteralPath $Path -Raw -Encoding UTF8|ConvertFrom-Json}catch{throw "$Code`:INVALID_JSON"};if($null-eq$v-or$v-is[array]){throw "$Code`:OBJECT_REQUIRED"};$v}
function Tree([string]$Path){$full=[IO.Path]::GetFullPath($Path).TrimEnd('\');$rows=@(Get-ChildItem -LiteralPath $full -Recurse -File -Force|Where-Object{$_.Name-notmatch'\.(pyc|pyo)$'-and$_.FullName-notmatch'[\\/]__pycache__[\\/]'}|Sort-Object FullName|ForEach-Object{"$($_.FullName.Substring($full.Length).TrimStart('\').Replace('\','/'))|$([long]$_.Length)|$(Sha $_.FullName)"});$h=[Security.Cryptography.SHA256]::Create();try{$d=([BitConverter]::ToString($h.ComputeHash([Text.Encoding]::UTF8.GetBytes(($rows-join"`n"))))).Replace('-','').ToLowerInvariant()}finally{$h.Dispose()};[ordered]@{file_count=$rows.Count;sha256=$d}}
function AssertNoReparse([string]$Path){$item=Get-Item -LiteralPath $Path -Force;if($item.Attributes-band[IO.FileAttributes]::ReparsePoint){throw 'R123_REPARSE_REJECTED'};$bad=@(Get-ChildItem -LiteralPath $Path -Recurse -Force|Where-Object{$_.Attributes-band[IO.FileAttributes]::ReparsePoint});if($bad.Count){throw 'R123_REPARSE_REJECTED'}}
function InspectZip([string]$Path){Add-Type -AssemblyName System.IO.Compression.FileSystem;$stream=[IO.File]::OpenRead($Path);$zip=[IO.Compression.ZipArchive]::new($stream,[IO.Compression.ZipArchiveMode]::Read,$false);try{$seen=[Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal);$files=0;$directories=0;foreach($entry in $zip.Entries){$raw=[string]$entry.FullName;$normalized=$raw.Replace('\','/');$directory=$normalized.EndsWith('/');$candidate=$normalized.TrimEnd('/');$parts=@($candidate.Split('/'));$mode=([int64]$entry.ExternalAttributes-shr16)-band0xF000;if(-not$raw-or$raw.Contains('\')-or$normalized.StartsWith('/')-or$candidate-match'^[A-Za-z]:'-or$candidate.Contains([char]0)-or$parts.Count-eq0-or@($parts|Where-Object{$_-in@('','.', '..')}).Count-or$mode-eq0xA000){throw 'R123_ZIP_UNSAFE_MEMBER'};if(-not$seen.Add($normalized)){throw 'R123_ZIP_DUPLICATE_MEMBER'};if($directory){$directories++}else{$files++}};if($files-ne33){throw 'R123_ZIP_FILE_COUNT_REJECTED'};[ordered]@{regular_files=$files;directories=$directories;unsafe=0;duplicates=0;symlinks=0}}finally{$zip.Dispose();$stream.Dispose()}}
function RuntimeInfo{$config=ReadObj (Join-Path $root 'config\node-config.json') 'R123_NODE_CONFIG';$manifest=ReadObj (Join-Path ([string]$config.web_runtime_root) 'runtime-build-manifest.json') 'R123_WEB_MANIFEST';[ordered]@{config=$config;manifest=$manifest}}
function Headers{$config=(RuntimeInfo).config;$path=Join-Path ([string]$config.data_root) 'workspace\runtime\runtime.token';if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw 'R123_RUNTIME_TOKEN_MISSING'};$token=(Get-Content -LiteralPath $path -Raw -Encoding ASCII).Trim();if($token-cnotmatch'^[A-Za-z0-9_-]{32,128}$'){throw 'R123_RUNTIME_TOKEN_INVALID'};@{Authorization='Bearer '+$token}}
function Api([string]$Path){Invoke-RestMethod -Method Get -Uri ('http://127.0.0.1:8765'+$Path) -Headers (Headers) -TimeoutSec 30}
function Health([string]$Uri){$rows=@();foreach($number in 1..3){$response=Invoke-WebRequest -Uri $Uri -UseBasicParsing -TimeoutSec 15;$payload=$response.Content|ConvertFrom-Json;if([int]$response.StatusCode-ne200-or-not[bool]$payload.ok-or[string]$payload.status-cne'ready'-or[string]$payload.build_id-cne$fixedWebBuild-or@($payload.failures).Count-ne0){throw 'R123_HEALTH_REJECTED'};$rows+=[ordered]@{sample=$number;status_code=200;build_id=$fixedWebBuild;exact=$true};if($number-lt3){Start-Sleep -Milliseconds 250}};[ordered]@{status='ready';samples=$rows}}
function Managed{$task=Get-ScheduledTask -TaskPath '\' -TaskName 'EvoMind-Cloud-Node' -ErrorAction Stop;$taskInfo=Get-ScheduledTaskInfo -TaskPath '\' -TaskName 'EvoMind-Cloud-Node' -ErrorAction Stop;if([string]$task.State-cne'Ready'-or[int64]$taskInfo.LastTaskResult-ne0-or[string]$task.Actions[0].Arguments-cnotmatch'-Action Start(?:\s|$)'){throw 'R123_MANAGED_TASK_REJECTED'};$state=ReadObj (Join-Path $root 'state\node-processes.json') 'R123_NODE_STATE';$roles=[ordered]@{};foreach($role in @('tenant_enrollment_queue','llm_gateway','python_runtime','web')){$rows=@($state.records|Where-Object{[string]$_.role-ceq$role});if($rows.Count-ne1){throw "R123_ROLE_COUNT:$role"};$processId=[int]$rows[0].pid;$process=Get-CimInstance Win32_Process -Filter "ProcessId=$processId";$owner=$process|Invoke-CimMethod -MethodName GetOwner;if([string]$owner.User-cne'EvoMindSvc'){throw "R123_ROLE_OWNER:$role"};$roles[$role]=[ordered]@{pid=$processId;owner='EvoMindSvc';name=[string]$process.Name}};$listeners=[ordered]@{};foreach($port in @(65068,8765,8088,7890)){$rows=@(Get-NetTCPConnection -State Listen -LocalPort $port -ErrorAction SilentlyContinue);if($rows.Count-ne1){throw "R123_LISTENER_COUNT:$port"};$process=Get-CimInstance Win32_Process -Filter "ProcessId=$([int]$rows[0].OwningProcess)";$owner=$process|Invoke-CimMethod -MethodName GetOwner;if([string]$owner.User-cne'EvoMindSvc'){throw "R123_LISTENER_OWNER:$port"};$listeners[[string]$port]=[ordered]@{pid=[int]$rows[0].OwningProcess;owner='EvoMindSvc';name=[string]$process.Name}};if(@($roles.Values|ForEach-Object{[int]$_.pid}|Select-Object -Unique).Count-ne4-or@($listeners.Values|ForEach-Object{[int]$_.pid}|Select-Object -Unique).Count-ne4){throw 'R123_MANAGED_PID_DUPLICATE'};[ordered]@{roles=$roles;listeners=$listeners;state_sha256=Sha (Join-Path $root 'state\node-processes.json')}}
function AssertFresh([object]$Before,[object]$After){foreach($role in @('tenant_enrollment_queue','llm_gateway','python_runtime','web')){if([int]$Before.roles[$role].pid-eq[int]$After.roles[$role].pid){throw "R123_ROLE_NOT_FRESH:$role"}};foreach($port in @('65068','8765','8088','7890')){if([int]$Before.listeners[$port].pid-eq[int]$After.listeners[$port].pid){throw "R123_LISTENER_NOT_FRESH:$port"}}}
function RunGate{$snapshot=Api "/v1/runs/$fixedRun";$active=@($snapshot.active_tool_calls).Count;$pending=@($snapshot.approvals|Where-Object{[string]$_.status-ceq'pending'}).Count;if([string]$snapshot.id-cne$fixedRun-or[string]$snapshot.status-cne'cancelled'-or-not[bool]$snapshot.terminal-or$active-ne0-or$pending-ne0){throw 'R123_RUN_GATE_REJECTED'};[ordered]@{run_id=$fixedRun;status='cancelled';terminal=$true;effective_active_count=0;pending_approval_count=0;last_event_seq=if($snapshot.PSObject.Properties.Name-contains'last_event_seq'){[int64]$snapshot.last_event_seq}else{[int64]0}}}
function GoalGate{$goal=Api '/v1/goals/goal_g21_five_competition';if([string]$goal.run_id-cne$fixedRun-or[string]$goal.allocation-cne$legacyGoalAllocation-or[string]$goal.status-cne'blocked'-or[string]$goal.spec_sha256-cne$goalSpecSha-or[string]$goal.board_sha256-cne$goalBoardSha){throw 'R123_GOAL_BINDING_REJECTED'};[ordered]@{id=[string]$goal.id;allocation=[string]$goal.allocation;status=[string]$goal.status;spec_sha256=[string]$goal.spec_sha256;board_sha256=[string]$goal.board_sha256;human_baseline_sha256=[string]$goal.human_baseline_sha256;updated_at=[string]$goal.updated_at}}
function Boundary{$info=RuntimeInfo;$bindingPath=Join-Path $root "byoa\tenants\$fixedTenant\hpc-binding.json";$binding=ReadObj $bindingPath 'R123_HPC_BINDING';$profileName="${fixedTenant}_job${fixedJob}_g${fixedGeneration}";if([string]$binding.schema-cne'evomind.tenant_hpc_binding.v1'-or[string]$binding.tenant_id-cne$fixedTenant-or[string]$binding.state-cne'active'-or[int]$binding.job_id-ne$fixedJob-or[int]$binding.allocation_generation-ne$fixedGeneration-or[string]$binding.credential_profile-cne$profileName){throw 'R123_G24_BINDING_REJECTED'};$profileInfo=Get-CimInstance Win32_UserProfile -ErrorAction SilentlyContinue|Where-Object{[IO.Path]::GetFileName(([string]$_.LocalPath).TrimEnd('\'))-ieq[string]$info.config.dedicated_user}|Select-Object -First 1;$profileHome=if($profileInfo){[string]$profileInfo.LocalPath}else{"C:\Users\$([string]$info.config.dedicated_user)"};$profilePath=Join-Path $profileHome "AppData\Roaming\ResearchAgentWorkstation\profiles\$profileName";if(-not(Test-Path -LiteralPath $profilePath -PathType Container)){throw 'R123_G24_PROFILE_MISSING'};if((Test-Path -LiteralPath (Join-Path $profilePath 'hpc_profile_frozen.tombstone.json'))-or(Test-Path -LiteralPath (Join-Path $profilePath 'hpc_profile_retired.tombstone.json'))){throw 'R123_G24_PROFILE_TOMBSTONED'};[ordered]@{binding_sha256=Sha $bindingPath;byoa_tree=Tree (Join-Path $root 'byoa');profile_root=$profilePath;profile_tree=Tree $profilePath;job_id=$fixedJob;allocation_generation=$fixedGeneration;state='active';credential_profile=$profileName}}
function SameBoundary([object]$A,[object]$B){if($A.binding_sha256-cne$B.binding_sha256-or$A.byoa_tree.file_count-ne$B.byoa_tree.file_count-or$A.byoa_tree.sha256-cne$B.byoa_tree.sha256-or$A.profile_root-cne$B.profile_root-or$A.profile_tree.file_count-ne$B.profile_tree.file_count-or$A.profile_tree.sha256-cne$B.profile_tree.sha256-or$A.job_id-ne$B.job_id-or$A.allocation_generation-ne$B.allocation_generation-or$A.state-cne$B.state-or$A.credential_profile-cne$B.credential_profile){throw 'R123_HPC_BYOA_BOUNDARY_CHANGED'}}
function InvokeManaged([ValidateSet('Stop','Start')][string]$Name){if(-not(Test-Path -LiteralPath $action -PathType Leaf)){throw 'R123_SERVICE_ACTION_MISSING'};$result=@(& $action -Action $Name -TimeoutMinutes 12)|Out-String|ConvertFrom-Json;if([string]$result.status-cne'completed'-or[string]$result.action-cne$Name){throw "R123_MANAGED_$($Name.ToUpperInvariant())_FAILED"};$result}
function AssertStopped{if(@(Get-NetTCPConnection -State Listen -ErrorAction SilentlyContinue|Where-Object{$_.LocalPort-in@(65068,8765,8088,7890)}).Count){throw 'R123_STOP_LISTENERS_REMAIN'}}
function BackupDb([string]$BackupRoot,[object]$Config){$db=Join-Path ([string]$Config.data_root) 'workspace\runtime\runtime.sqlite3';if(-not(Test-Path -LiteralPath $db -PathType Leaf)){throw 'R123_DB_MISSING'};$directory=Join-Path $BackupRoot 'database';New-Item -ItemType Directory -Path $directory|Out-Null;$rows=@();foreach($suffix in @('','-wal','-shm')){$source="$db$suffix";$exists=Test-Path -LiteralPath $source -PathType Leaf;$row=[ordered]@{suffix=$suffix;existed=$exists;bytes=0;sha256=''};if($exists){$name=if($suffix){"runtime.sqlite3$suffix"}else{'runtime.sqlite3'};Copy-Item -LiteralPath $source -Destination (Join-Path $directory $name);$row.bytes=[long](Get-Item -LiteralPath $source).Length;$row.sha256=Sha $source};$rows+=[pscustomobject]$row};[ordered]@{path=$db;files=$rows}}
function RestoreDb([string]$BackupRoot,[object]$Backup){foreach($suffix in @('','-wal','-shm')){$path="$($Backup.path)$suffix";if(Test-Path -LiteralPath $path){Remove-Item -LiteralPath $path -Force}};foreach($row in @($Backup.files)){if([bool]$row.existed){$name=if([string]$row.suffix){"runtime.sqlite3$([string]$row.suffix)"}else{'runtime.sqlite3'};Copy-Item -LiteralPath (Join-Path (Join-Path $BackupRoot 'database') $name) -Destination "$($Backup.path)$([string]$row.suffix)"}}}
function AssertRestoredDb([object]$Backup){foreach($row in @($Backup.files)){$path="$($Backup.path)$([string]$row.suffix)";if([bool]$row.existed){if(-not(Test-Path -LiteralPath $path -PathType Leaf)-or[long](Get-Item -LiteralPath $path).Length-ne[long]$row.bytes-or(Sha $path)-cne[string]$row.sha256){throw 'R123_ROLLBACK_DB_HASH_REJECTED'}}elseif(Test-Path -LiteralPath $path){throw 'R123_ROLLBACK_DB_UNEXPECTED_FILE'}}}
function Inputs{$approval=ReadObj $approvalPath 'R123_APPROVAL';if((Sha $approvalPath)-cne$ApprovalSha256-or[string]$approval.schema-cne'evomind.managed_hpc_identity_rebind_runtime_deployment_approval.r123.v1'-or[string]$approval.status-cne'approved_for_single_runtime_transaction'-or[string]$approval.deployment_id-cne$TransactionId-or[string]$approval.run_id-cne$fixedRun-or[string]$approval.target_allocation-cne$targetAllocation-or[int]$approval.target_job_id-ne$fixedJob-or[string]$approval.candidate.installed_runtime_tree_sha256-cne$candidateTreeSha-or[string]$approval.baseline.zip_sha256-cne$baselineZipSha-or[string]$approval.baseline.runtime_tree_sha256-cne$baselineTreeSha-or[string]$approval.baseline.manifest_sha256-cne$baselineManifestSha-or[string]$approval.deployer.remote_runner_sha256-cne(Sha $PSCommandPath)){throw 'R123_APPROVAL_REJECTED'};foreach($input in @([pscustomobject]@{path=$archive;sha=[string]$approval.candidate.sha256},[pscustomobject]@{path=$sourceManifestPath;sha=[string]$approval.candidate.source_manifest_sha256},[pscustomobject]@{path=$buildResultPath;sha=[string]$approval.candidate.build_result_sha256},[pscustomobject]@{path=$receiptPath;sha=[string]$approval.verification.test_receipt_sha256})){if((Sha $input.path)-cne$input.sha){throw 'R123_INPUT_HASH_REJECTED'}};$approval}
function Candidate([object]$Approval){if(Test-Path -LiteralPath $stage){throw 'R123_STAGE_EXISTS'};$zipInspection=InspectZip $archive;Expand-Archive -LiteralPath $archive -DestinationPath $stage;AssertNoReparse $stage;$manifestPath=Join-Path $stage $manifestName;$manifest=ReadObj $manifestPath 'R123_MANIFEST';if((Sha $manifestPath)-cne(Sha $sourceManifestPath)-or[string]$manifest.schema-cne'evomind.managed_hpc_identity_rebind_runtime.r123.v1'-or[string]$manifest.candidate_runtime_tree_sha256-cne$candidateTreeSha-or[int]$manifest.candidate_runtime_file_count-ne32-or[int]$manifest.changed_file_count-ne3-or[int]$manifest.unchanged_file_count-ne29-or(($manifest.changed_files-join'|')-cne($changedFiles-join'|'))-or[bool]$manifest.production_deployable-or[bool]$manifest.production_deployed){throw 'R123_MANIFEST_REJECTED'};$declared=@{};foreach($entry in @($manifest.files)){$path=[string]$entry.path;if($path-cnotmatch'^evomind_runtime/[A-Za-z0-9_]+\.py$'-or$declared.ContainsKey($path)){throw 'R123_MANIFEST_ENTRY_REJECTED'};$declared[$path]=$entry};$actual=@(Get-ChildItem -LiteralPath $stage -Recurse -File -Force|ForEach-Object{$_.FullName.Substring($stage.Length+1).Replace('\','/')}|Where-Object{$_-ne$manifestName});if($declared.Count-ne32-or$actual.Count-ne32-or@($actual|Where-Object{-not$declared.ContainsKey($_)}).Count){throw 'R123_FILESET_REJECTED'};foreach($path in $declared.Keys){$file=Join-Path $stage $path.Replace('/','\');$entry=$declared[$path];if((Get-Item -LiteralPath $file).Length-ne[long]$entry.bytes-or(Sha $file)-cne[string]$entry.sha256){throw 'R123_FILE_HASH_REJECTED'}};$candidatePath=Join-Path $stage 'evomind_runtime';$tree=Tree $candidatePath;if($tree.file_count-ne32-or$tree.sha256-cne$candidateTreeSha){throw 'R123_TREE_REJECTED'};[ordered]@{path=$candidatePath;tree=$tree;manifest=$manifest;zip_inspection=$zipInspection}}

if((Test-Path -LiteralPath $resultPath)-or(Test-Path -LiteralPath $errorPath)){throw 'R123_RESULT_EXISTS'}
$mutex=[Threading.Mutex]::new($false,'Global\EvoMind-Byoa-V12-Deployment');$owned=$false;$backup=$null;$candidate=$null;$bundleCandidate=$null;$targetBackedUp=$false;$serviceStopped=$false;$databaseBackup=$null;$boundaryBefore=$null
try{
  $owned=$mutex.WaitOne([TimeSpan]::FromSeconds(10));if(-not$owned){throw 'R123_DEPLOYMENT_LOCKED'}
  $approval=Inputs;$candidate=Candidate $approval
  $preLoopback=Health 'http://127.0.0.1:8088/api/healthz';$prePublic=Health 'https://evomind.zhjjq.tech/api/healthz'
  $managedBefore=Managed;$runBefore=RunGate;$goalBefore=GoalGate;$current=Tree $target;if($current.file_count-ne32-or$current.sha256-cne$baselineTreeSha){throw 'R123_CURRENT_RUNTIME_NOT_R121'}
  $runtimeInfo=RuntimeInfo;$webRoot=[string]$runtimeInfo.config.web_runtime_root;$webBefore=Tree $webRoot;$boundaryBefore=Boundary
  InvokeManaged Stop|Out-Null;$serviceStopped=$true;AssertStopped
  $backup=Join-Path "$root\backups" ('pre-r123-managed-hpc-rebind-'+[DateTime]::UtcNow.ToString('yyyyMMddTHHmmssZ')+'-'+$TransactionId)
  New-Item -ItemType Directory -Path (Join-Path $backup 'original')|Out-Null
  $databaseBackup=BackupDb $backup $runtimeInfo.config
  Copy-Item -LiteralPath $approvalPath -Destination (Join-Path $backup 'approval.json')
  WriteJson (Join-Path $backup 'backup-manifest.json') ([ordered]@{schema='evomind.managed_hpc_identity_rebind_runtime_backup.r123.v1';transaction_id=$TransactionId;approval_sha256=$ApprovalSha256;old_runtime_tree=$current;new_runtime_tree=$candidate.tree;database=$databaseBackup;boundary=$boundaryBefore})
  $bundleCandidate=Join-Path $bundleRuntime "evomind_runtime.$TransactionId.stage"
  Move-Item -LiteralPath $candidate.path -Destination $bundleCandidate
  Move-Item -LiteralPath $target -Destination (Join-Path $backup 'original\evomind_runtime');$targetBackedUp=$true
  Move-Item -LiteralPath $bundleCandidate -Destination $target
  & $seal|Out-Null
  $installed=Tree $target;if($installed.file_count-ne32-or$installed.sha256-cne$candidateTreeSha){throw 'R123_INSTALLED_TREE_REJECTED'}
  $boundaryDuring=Boundary;SameBoundary $boundaryBefore $boundaryDuring
  InvokeManaged Start|Out-Null;$serviceStopped=$false
  $loopback=Health 'http://127.0.0.1:8088/api/healthz';$public=Health 'https://evomind.zhjjq.tech/api/healthz'
  $managedAfter=Managed;AssertFresh $managedBefore $managedAfter
  $runAfter=RunGate;if($runAfter.status-cne$runBefore.status-or$runAfter.last_event_seq-ne$runBefore.last_event_seq){throw 'R123_RUN_CHANGED'}
  $goalAfter=GoalGate;if(($goalAfter|ConvertTo-Json -Compress)-cne($goalBefore|ConvertTo-Json -Compress)){throw 'R123_GOAL_CHANGED'}
  $boundaryAfter=Boundary;SameBoundary $boundaryBefore $boundaryAfter
  $webAfter=Tree $webRoot;if($webAfter.file_count-ne$webBefore.file_count-or$webAfter.sha256-cne$webBefore.sha256){throw 'R123_WEB_CHANGED'}
  $final=Tree $target;if($final.sha256-cne$candidateTreeSha){throw 'R123_FINAL_TREE_REJECTED'}
  $payload=[ordered]@{schema='evomind.managed_hpc_identity_rebind_runtime_deployment_result.r123.v1';status='installed_and_verified';transaction_id=$TransactionId;approval_sha256=$ApprovalSha256;web_build_id=$fixedWebBuild;candidate_zip_inspection=$candidate.zip_inspection;pre_loopback=$preLoopback;pre_public=$prePublic;loopback=$loopback;public=$public;managed_before=$managedBefore;managed_after=$managedAfter;run_before=$runBefore;run_after=$runAfter;run_unchanged=$true;goal_before=$goalBefore;goal_after=$goalAfter;goal_unchanged=$true;old_runtime_tree=$current;installed_runtime_tree=$final;backup_root=$backup;database_backup=$databaseBackup;web_tree_unchanged=$true;g24_before=$boundaryBefore;g24_after=$boundaryAfter;hpc_binding_unchanged=$true;byoa_unchanged=$true;profile_unchanged=$true;hpc_accessed=$false;gpu_touched=$false;hpc_remote_writes=0;direct_signals_sent=0;other_processes_modified=$false;training_started=$false;hpc_tool_calls=0;managed_service_actions=@('Stop','Start')}
  WriteJson $resultPath $payload;$payload|ConvertTo-Json -Depth 40 -Compress
}catch{
  $failure=$_;$rollback='not_required';$rollbackError=$null
  if($targetBackedUp){try{if(-not$serviceStopped){InvokeManaged Stop|Out-Null;$serviceStopped=$true;AssertStopped};if(Test-Path -LiteralPath $target){Remove-Item -LiteralPath $target -Recurse -Force};Move-Item -LiteralPath (Join-Path $backup 'original\evomind_runtime') -Destination $target;RestoreDb $backup $databaseBackup;$restored=Tree $target;if($restored.file_count-ne32-or$restored.sha256-cne$baselineTreeSha){throw 'R123_ROLLBACK_RUNTIME_HASH_REJECTED'};AssertRestoredDb $databaseBackup;& $seal|Out-Null;InvokeManaged Start|Out-Null;$serviceStopped=$false;Health 'http://127.0.0.1:8088/api/healthz'|Out-Null;$rollback='restored_and_verified'}catch{$rollback='failed';$rollbackError=SafeError $_.Exception.Message}}
  elseif($serviceStopped){try{InvokeManaged Start|Out-Null;$serviceStopped=$false;Health 'http://127.0.0.1:8088/api/healthz'|Out-Null;$rollback='start_only_recovered'}catch{$rollback='failed';$rollbackError=SafeError $_.Exception.Message}}
  $safe=SafeError $failure.Exception.Message;WriteJson $errorPath ([ordered]@{schema='evomind.managed_hpc_identity_rebind_runtime_deployment_error.r123.v1';status='failed';transaction_id=$TransactionId;approval_sha256=$ApprovalSha256;message=$safe;rollback=$rollback;rollback_error=$rollbackError;hpc_accessed=$false;gpu_touched=$false;hpc_remote_writes=0;direct_signals_sent=0;other_processes_modified=$false});throw
}finally{if($owned){try{[void]$mutex.ReleaseMutex()}catch{}};$mutex.Dispose()}
