param(
  [Parameter(Mandatory)][string]$ApprovalPath,
  [switch]$ValidateOnly
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$approvalSchema='evomind.g21_terminal_preserving_probe_runtime_deployment_approval.r120.v1'
$releaseSchema='evomind.g21_terminal_preserving_probe_runtime.r120.v1'
$receiptSchema='evomind.g21_terminal_preserving_probe_runtime_test_receipt.r120.v1'
$fixedRun='run_7b1efb878afb40f396db431e91f093a5'
$fixedAllocation='G21'
$fixedWebBuild='overlay-controlled-secret-binding-r112-standalone-f38c40f2dbdc'
$baselineZipSha='9368c7962632fb976e7a8ba8ede0d3108989e96c00c4dd75bca154008d438206'
$baselineTreeSha='906868d22a841f591fb84c7a505b75acee3c8df58f179e83d3d4585601d03975'
$baselineManifestSha='12f80d02d6fd87e413c57bc606d09a27f90c3edac3b4b1d7462826374666b9ac'
$candidateTreeSha='5998ea21823c121c23a421bb145d8e2266bb79ab59eccc91a16122c3626b61ce'
$hostAlias='evomind-shanghai'
$runnerName='Deploy-G21TerminalPreservingProbeRuntimeR120Remote.ps1'
$runner=Join-Path $PSScriptRoot $runnerName
$sshOptions=@('-o','ConnectionAttempts=3','-o','ConnectTimeout=30','-o','ServerAliveInterval=10','-o','ServerAliveCountMax=3')

function Sha([string]$Path){$stream=[IO.File]::OpenRead($Path);$hash=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($hash.ComputeHash($stream))).Replace('-','').ToLowerInvariant()}finally{$stream.Dispose();$hash.Dispose()}}
function Read-Object([string]$Path,[string]$Code){if(-not(Test-Path -LiteralPath $Path -PathType Leaf)){throw "$Code`:MISSING"};try{$value=Get-Content -LiteralPath $Path -Raw -Encoding UTF8|ConvertFrom-Json}catch{throw "$Code`:INVALID_JSON"};if($null-eq$value-or$value-is[array]){throw "$Code`:OBJECT_REQUIRED"};$value}
function Resolve-Bound([string]$Directory,[object]$Entry,[string]$Code){$name=[string]$Entry.filename;if($name-cnotmatch'^[A-Za-z0-9][A-Za-z0-9._-]{0,199}$'-or[IO.Path]::GetFileName($name)-cne$name-or[string]$Entry.sha256-cnotmatch'^[a-f0-9]{64}$'){throw "$Code`:ENTRY_REJECTED"};$path=[IO.Path]::GetFullPath((Join-Path $Directory $name));if([IO.Path]::GetDirectoryName($path).TrimEnd('\')-cne[IO.Path]::GetFullPath($Directory).TrimEnd('\')-or-not(Test-Path -LiteralPath $path -PathType Leaf)-or(Sha $path)-cne[string]$Entry.sha256){throw "$Code`:HASH_OR_PATH_REJECTED"};[ordered]@{path=$path;filename=$name;sha256=[string]$Entry.sha256}}

function Read-Approval([string]$Path){
  $full=[IO.Path]::GetFullPath($Path);$approval=Read-Object $full 'R120_APPROVAL';$directory=[IO.Path]::GetDirectoryName($full)
  $statusAllowed=if($ValidateOnly){[string]$approval.status-in@('validation_only_non_authorizing','approved_for_single_runtime_transaction')}else{[string]$approval.status-ceq'approved_for_single_runtime_transaction'}
  if([string]$approval.schema-cne$approvalSchema-or-not$statusAllowed-or-not[bool]$approval.one_time-or[string]$approval.deployment_id-cnotmatch'^[a-f0-9]{32}$'-or[string]$approval.run_id-cne$fixedRun-or[string]$approval.allocation-cne$fixedAllocation-or[string]$approval.web_build_id-cne$fixedWebBuild-or[string]$approval.preflight.run_status_required-cne'cancelled'-or-not[bool]$approval.preflight.run_terminal_required-or[int]$approval.preflight.effective_active_required-ne0-or[int]$approval.preflight.pending_approvals_required-ne0-or[string]$approval.preflight.current_runtime_tree_sha256-cne$baselineTreeSha-or[string]$approval.baseline.zip_sha256-cne$baselineZipSha-or[string]$approval.baseline.runtime_tree_sha256-cne$baselineTreeSha-or[string]$approval.baseline.manifest_sha256-cne$baselineManifestSha-or[string]$approval.candidate.installed_runtime_tree_sha256-cne$candidateTreeSha-or[int]$approval.candidate.runtime_file_count-ne32-or[int]$approval.candidate.changed_file_count-ne1-or[int]$approval.candidate.unchanged_file_count-ne31-or[string]$approval.candidate.changed_files[0]-cne'evomind_runtime/http_server.py'-or[string]$approval.transport.mode-cne'single_scp_envelope'-or-not[bool]$approval.boundaries.runtime_only-or-not[bool]$approval.boundaries.hpc_access_forbidden){throw 'R120_APPROVAL_CONTRACT_REJECTED'}
  try{$created=[DateTimeOffset]::Parse([string]$approval.created_at);$expires=[DateTimeOffset]::Parse([string]$approval.expires_at)}catch{throw 'R120_APPROVAL_TIME_REJECTED'};$now=[DateTimeOffset]::UtcNow;if($expires-le$created-or$now-lt$created.AddMinutes(-5)-or$now-ge$expires-or($expires-$created).TotalMinutes-gt60){throw 'R120_APPROVAL_EXPIRED'}
  $names=@('candidate','source_manifest','build_result','test_receipt','verifier','wrapper','remote_deployer','probe_wrapper','probe_remote_runner');$inputs=[ordered]@{};foreach($name in $names){$inputs[$name]=Resolve-Bound $directory $approval.bound_inputs.$name "R120_$($name.ToUpperInvariant())"}
  if($inputs.wrapper.filename-cne[IO.Path]::GetFileName($PSCommandPath)-or(Sha $PSCommandPath)-cne$inputs.wrapper.sha256-or$inputs.remote_deployer.filename-cne$runnerName-or(Sha $runner)-cne$inputs.remote_deployer.sha256){throw 'R120_DEPLOYER_BINDING_REJECTED'}
  $manifest=Read-Object $inputs.source_manifest.path 'R120_SOURCE_MANIFEST';$build=Read-Object $inputs.build_result.path 'R120_BUILD_RESULT';$receipt=Read-Object $inputs.test_receipt.path 'R120_TEST_RECEIPT'
  if([string]$manifest.schema-cne$releaseSchema-or[string]$manifest.baseline_zip_sha256-cne$baselineZipSha-or[string]$manifest.baseline_runtime_tree_sha256-cne$baselineTreeSha-or[string]$manifest.baseline_manifest_sha256-cne$baselineManifestSha-or[string]$manifest.candidate_runtime_tree_sha256-cne[string]$approval.candidate.installed_runtime_tree_sha256-or[string]$manifest.changed_files[0]-cne'evomind_runtime/http_server.py'-or[bool]$manifest.production_deployable-or[bool]$manifest.production_deployed-or[string]$build.status-cne'built_and_verified'-or[string]$build.zip_sha256-cne$inputs.candidate.sha256-or[string]$build.source_manifest_sha256-cne$inputs.source_manifest.sha256-or[string]$receipt.schema-cne$receiptSchema-or[string]$receipt.status-cne'verified'-or[string]$receipt.candidate_zip_sha256-cne$inputs.candidate.sha256-or[string]$receipt.source_manifest_sha256-cne$inputs.source_manifest.sha256-or[string]$receipt.build_result_sha256-cne$inputs.build_result.sha256-or@($receipt.verification_rounds).Count-ne2){throw 'R120_RELEASE_BINDING_REJECTED'}
  [ordered]@{path=$full;directory=$directory;approval=$approval;inputs=$inputs}
}

$bound=Read-Approval $ApprovalPath;$approval=$bound.approval;$approvalSha=Sha $bound.path;$transactionId=[string]$approval.deployment_id
if($ValidateOnly){[ordered]@{schema=$approvalSchema;status='validated_not_deployed';deployment_id=$transactionId;run_id=$fixedRun;allocation=$fixedAllocation;approval_sha256=$approvalSha;candidate_sha256=$bound.inputs.candidate.sha256;candidate_tree_sha256=[string]$approval.candidate.installed_runtime_tree_sha256;production_action_performed=$false;hpc_accessed=$false;gpu_touched=$false;remote_writes=0}|ConvertTo-Json -Compress;exit 0}
$output=Join-Path $bound.directory "r120-terminal-preserving-probe-runtime-production-$transactionId.json";$errorOutput=[IO.Path]::ChangeExtension($output,'.error.json');if((Test-Path -LiteralPath $output)-or(Test-Path -LiteralPath $errorOutput)){throw 'R120_DEPLOY_OUTPUT_EXISTS'}
$remote="C:\SecureInput\r120-terminal-preserving-probe-runtime-$transactionId";$stage=Join-Path $bound.directory ('upload-staging-'+[guid]::NewGuid().ToString('N'));$envelope=Join-Path $bound.directory "upload-envelope-$transactionId.zip";New-Item -ItemType Directory -Path $stage|Out-Null
try{
  $uploads=@([pscustomobject]@{path=$bound.path;name='approval.json';sha=$approvalSha},[pscustomobject]@{path=$bound.inputs.candidate.path;name='runtime.zip';sha=$bound.inputs.candidate.sha256},[pscustomobject]@{path=$bound.inputs.source_manifest.path;name='source-manifest.json';sha=$bound.inputs.source_manifest.sha256},[pscustomobject]@{path=$bound.inputs.build_result.path;name='build-result.json';sha=$bound.inputs.build_result.sha256},[pscustomobject]@{path=$bound.inputs.test_receipt.path;name='test-receipt.json';sha=$bound.inputs.test_receipt.sha256},[pscustomobject]@{path=$bound.inputs.remote_deployer.path;name=$runnerName;sha=$bound.inputs.remote_deployer.sha256})
  foreach($item in $uploads){$target=Join-Path $stage $item.name;Copy-Item -LiteralPath $item.path -Destination $target;if((Sha $target)-cne$item.sha){throw 'R120_STAGING_HASH_REJECTED'}}
  Add-Type -AssemblyName System.IO.Compression.FileSystem;[IO.Compression.ZipFile]::CreateFromDirectory($stage,$envelope,[IO.Compression.CompressionLevel]::Optimal,$false);$envelopeSha=Sha $envelope
}finally{if(Test-Path -LiteralPath $stage){Remove-Item -LiteralPath $stage -Recurse -Force -ErrorAction SilentlyContinue}}
$create="if(Test-Path -LiteralPath '$remote'){throw 'R120_REMOTE_EXISTS'};New-Item -ItemType Directory -Path '$remote'|Out-Null";$create|& ssh @sshOptions $hostAlias powershell.exe -NoProfile -NonInteractive -Command -;if($LASTEXITCODE-ne0){throw 'R120_REMOTE_CREATE_FAILED'}
& scp @sshOptions $envelope "${hostAlias}:$remote\upload-envelope.zip";if($LASTEXITCODE-ne0){throw 'R120_ENVELOPE_UPLOAD_FAILED'}
$verify="function sh([string]`$p){`$s=[IO.File]::OpenRead(`$p);`$h=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString(`$h.ComputeHash(`$s))).Replace('-','').ToLowerInvariant()}finally{`$s.Dispose();`$h.Dispose()}};`$p=Join-Path '$remote' 'upload-envelope.zip';if((sh `$p)-cne'$envelopeSha'){throw 'R120_ENVELOPE_HASH_REJECTED'};Expand-Archive -LiteralPath `$p -DestinationPath (Join-Path '$remote' 'envelope-expanded')";$verify|& ssh @sshOptions $hostAlias powershell.exe -NoProfile -NonInteractive -Command -;if($LASTEXITCODE-ne0){throw 'R120_REMOTE_VERIFY_FAILED'}
& ssh @sshOptions $hostAlias "powershell.exe -NoProfile -NonInteractive -File $remote\envelope-expanded\$runnerName -TransactionId $transactionId -RemoteRoot $remote -ApprovalSha256 $approvalSha";if($LASTEXITCODE-ne0){& scp @sshOptions "${hostAlias}:$remote\transaction-$transactionId-error.json" $errorOutput 2>$null;throw 'R120_TRANSACTION_FAILED'}
& scp @sshOptions "${hostAlias}:$remote\transaction-$transactionId-result.json" $output;if($LASTEXITCODE-ne0-or-not(Test-Path -LiteralPath $output -PathType Leaf)){throw 'R120_RESULT_DOWNLOAD_FAILED'}
$result=Read-Object $output 'R120_RESULT';if([string]$result.schema-cne'evomind.g21_terminal_preserving_probe_runtime_deployment_result.r120.v1'-or[string]$result.status-cne'installed_and_verified'-or[string]$result.transaction_id-cne$transactionId-or[string]$result.approval_sha256-cne$approvalSha-or[string]$result.run_before.status-cne'cancelled'-or[string]$result.run_after.status-cne'cancelled'-or-not[bool]$result.run_after.terminal-or[int]$result.run_after.effective_active_count-ne0-or[int]$result.run_after.pending_approval_count-ne0-or[string]$result.installed_runtime_tree.sha256-cne[string]$approval.candidate.installed_runtime_tree_sha256-or-not[bool]$result.goal_unchanged-or-not[bool]$result.web_tree_unchanged-or-not[bool]$result.hpc_binding_unchanged-or[bool]$result.hpc_accessed-or[bool]$result.gpu_touched-or[int]$result.hpc_remote_writes-ne0-or[int]$result.direct_signals_sent-ne0-or[bool]$result.other_processes_modified-or[bool]$result.training_started-or[int]$result.hpc_tool_calls-ne0){throw 'R120_RESULT_REJECTED'}
[ordered]@{status='installed_and_verified';transaction_id=$transactionId;result_path=$output;result_sha256=Sha $output;run_id=$fixedRun;hpc_accessed=$false;gpu_touched=$false}|ConvertTo-Json -Compress
