param(
  [Parameter(Mandatory)][string]$ApprovalPath,
  [switch]$ValidateOnly
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$approvalSchema='evomind.managed_hpc_identity_rebind_runtime_deployment_approval.r123.v1'
$releaseSchema='evomind.managed_hpc_identity_rebind_runtime.r123.v1'
$receiptSchema='evomind.managed_hpc_identity_rebind_runtime_test_receipt.r123.v1'
$fixedRun='run_7b1efb878afb40f396db431e91f093a5'
$targetAllocation='G24'
$targetJob=93015
$fixedWebBuild='overlay-assistant-interaction-r122-1393046c9de7'
$baselineZipSha='f927d3538b6b1f1a02ed4fb57312d2663296e98baa56940660c321058440f4d2'
$baselineTreeSha='a9595ab4ed9a86786ca65f4456893d64741b449ec84cf8c9ddb42e9bf4110dc7'
$baselineManifestSha='d644dc05a01cc4fec0201716bbfdc7a108a7f412c9cc98edfe95ef7a3bac8da8'
$candidateTreeSha='4bb0803db0e0fed319e45f4ac39152382fdcb762650cb2009d1fcd2b0e9d17fc'
$hostAlias='evomind-shanghai'
$runnerName='Deploy-ManagedHpcIdentityRebindRuntimeR123Remote.ps1'
$runner=Join-Path $PSScriptRoot $runnerName
$sshOptions=@('-o','ConnectionAttempts=3','-o','ConnectTimeout=30','-o','ServerAliveInterval=10','-o','ServerAliveCountMax=3')
$changedFiles=@('evomind_runtime/assistant_runs.py','evomind_runtime/http_server.py','evomind_runtime/store.py')

function Sha([string]$Path){$stream=[IO.File]::OpenRead($Path);$hash=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($hash.ComputeHash($stream))).Replace('-','').ToLowerInvariant()}finally{$stream.Dispose();$hash.Dispose()}}
function ReadObj([string]$Path,[string]$Code){if(-not(Test-Path -LiteralPath $Path -PathType Leaf)){throw "$Code`:MISSING"};try{$value=Get-Content -LiteralPath $Path -Raw -Encoding UTF8|ConvertFrom-Json}catch{throw "$Code`:INVALID_JSON"};if($null-eq$value-or$value-is[array]){throw "$Code`:OBJECT_REQUIRED"};$value}
function ResolveBound([string]$Directory,[object]$Entry,[string]$Code){$name=[string]$Entry.filename;if($name-cnotmatch'^[A-Za-z0-9][A-Za-z0-9._-]{0,199}$'-or[IO.Path]::GetFileName($name)-cne$name-or[string]$Entry.sha256-cnotmatch'^[a-f0-9]{64}$'){throw "$Code`:ENTRY_REJECTED"};$path=[IO.Path]::GetFullPath((Join-Path $Directory $name));if([IO.Path]::GetDirectoryName($path).TrimEnd('\')-cne[IO.Path]::GetFullPath($Directory).TrimEnd('\')-or-not(Test-Path -LiteralPath $path -PathType Leaf)-or(Sha $path)-cne[string]$Entry.sha256){throw "$Code`:HASH_OR_PATH_REJECTED"};[ordered]@{path=$path;filename=$name;sha256=[string]$Entry.sha256}}

function ReadApproval([string]$Path){
  $full=[IO.Path]::GetFullPath($Path);$approval=ReadObj $full 'R123_APPROVAL';$directory=[IO.Path]::GetDirectoryName($full)
  $statusAllowed=if($ValidateOnly){[string]$approval.status-in@('validation_only_non_authorizing','approved_for_single_runtime_transaction')}else{[string]$approval.status-ceq'approved_for_single_runtime_transaction'}
  if([string]$approval.schema-cne$approvalSchema-or-not$statusAllowed-or-not[bool]$approval.one_time-or[string]$approval.deployment_id-cnotmatch'^[a-f0-9]{32}$'-or[string]$approval.run_id-cne$fixedRun-or[string]$approval.target_allocation-cne$targetAllocation-or[int]$approval.target_job_id-ne$targetJob-or[string]$approval.web_build_id-cne$fixedWebBuild-or[string]$approval.preflight.run_status_required-cne'cancelled'-or-not[bool]$approval.preflight.run_terminal_required-or[int]$approval.preflight.effective_active_required-ne0-or[int]$approval.preflight.pending_approvals_required-ne0-or[string]$approval.preflight.current_runtime_tree_sha256-cne$baselineTreeSha-or[string]$approval.baseline.zip_sha256-cne$baselineZipSha-or[string]$approval.baseline.runtime_tree_sha256-cne$baselineTreeSha-or[string]$approval.baseline.manifest_sha256-cne$baselineManifestSha-or[string]$approval.candidate.installed_runtime_tree_sha256-cne$candidateTreeSha-or[int]$approval.candidate.runtime_file_count-ne32-or[int]$approval.candidate.changed_file_count-ne3-or[int]$approval.candidate.unchanged_file_count-ne29-or(($approval.candidate.changed_files-join'|')-cne($changedFiles-join'|'))-or[string]$approval.transport.mode-cne'single_scp_envelope'-or-not[bool]$approval.boundaries.runtime_only-or-not[bool]$approval.boundaries.hpc_access_forbidden-or-not[bool]$approval.boundaries.web_immutable-or-not[bool]$approval.boundaries.goal_immutable){throw 'R123_APPROVAL_CONTRACT_REJECTED'}
  try{$created=[DateTimeOffset]::Parse([string]$approval.created_at);$expires=[DateTimeOffset]::Parse([string]$approval.expires_at)}catch{throw 'R123_APPROVAL_TIME_REJECTED'};$now=[DateTimeOffset]::UtcNow;if($expires-le$created-or$now-lt$created.AddMinutes(-5)-or$now-ge$expires-or($expires-$created).TotalMinutes-gt60){throw 'R123_APPROVAL_EXPIRED'}
  $names=@('candidate','source_manifest','build_result','test_receipt','verifier','wrapper','remote_deployer');$inputs=[ordered]@{};foreach($name in $names){$inputs[$name]=ResolveBound $directory $approval.bound_inputs.$name "R123_$($name.ToUpperInvariant())"}
  if($inputs.wrapper.filename-cne[IO.Path]::GetFileName($PSCommandPath)-or(Sha $PSCommandPath)-cne$inputs.wrapper.sha256-or$inputs.remote_deployer.filename-cne$runnerName-or(Sha $runner)-cne$inputs.remote_deployer.sha256){throw 'R123_DEPLOYER_BINDING_REJECTED'}
  $manifest=ReadObj $inputs.source_manifest.path 'R123_SOURCE_MANIFEST';$build=ReadObj $inputs.build_result.path 'R123_BUILD_RESULT';$receipt=ReadObj $inputs.test_receipt.path 'R123_TEST_RECEIPT'
  if([string]$manifest.schema-cne$releaseSchema-or[string]$manifest.run_id-cne$fixedRun-or[string]$manifest.target_allocation-cne$targetAllocation-or[int]$manifest.target_job_id-ne$targetJob-or[string]$manifest.baseline_zip_sha256-cne$baselineZipSha-or[string]$manifest.baseline_runtime_tree_sha256-cne$baselineTreeSha-or[string]$manifest.baseline_manifest_sha256-cne$baselineManifestSha-or[string]$manifest.candidate_runtime_tree_sha256-cne$candidateTreeSha-or(($manifest.changed_files-join'|')-cne($changedFiles-join'|'))-or[bool]$manifest.production_deployable-or[bool]$manifest.production_deployed-or[string]$build.schema-cne$releaseSchema-or[string]$build.status-cne'built_and_verified'-or[string]$build.zip_sha256-cne$inputs.candidate.sha256-or[string]$build.source_manifest_sha256-cne$inputs.source_manifest.sha256-or[string]$build.candidate_runtime_tree_sha256-cne$candidateTreeSha-or[string]$receipt.schema-cne$receiptSchema-or[string]$receipt.status-cne'verified'-or[string]$receipt.candidate_zip_sha256-cne$inputs.candidate.sha256-or[string]$receipt.source_manifest_sha256-cne$inputs.source_manifest.sha256-or[string]$receipt.build_result_sha256-cne$inputs.build_result.sha256-or[string]$receipt.candidate_runtime_tree_sha256-cne$candidateTreeSha-or@($receipt.verification_rounds).Count-ne2){throw 'R123_RELEASE_BINDING_REJECTED'}
  [ordered]@{path=$full;directory=$directory;approval=$approval;inputs=$inputs}
}

$bound=ReadApproval $ApprovalPath;$approval=$bound.approval;$approvalSha=Sha $bound.path;$transactionId=[string]$approval.deployment_id
if($ValidateOnly){[ordered]@{schema=$approvalSchema;status='validated_not_deployed';deployment_id=$transactionId;run_id=$fixedRun;target_allocation=$targetAllocation;target_job_id=$targetJob;approval_sha256=$approvalSha;candidate_sha256=$bound.inputs.candidate.sha256;candidate_tree_sha256=[string]$approval.candidate.installed_runtime_tree_sha256;production_action_performed=$false;hpc_accessed=$false;gpu_touched=$false;remote_writes=0}|ConvertTo-Json -Compress;exit 0}
$output=Join-Path $bound.directory "r123-managed-hpc-rebind-runtime-production-$transactionId.json";$errorOutput=[IO.Path]::ChangeExtension($output,'.error.json');if((Test-Path -LiteralPath $output)-or(Test-Path -LiteralPath $errorOutput)){throw 'R123_DEPLOY_OUTPUT_EXISTS'}
$remote="C:\SecureInput\r123-managed-hpc-rebind-runtime-$transactionId";$stage=Join-Path $bound.directory ('upload-staging-'+[guid]::NewGuid().ToString('N'));$envelope=Join-Path $bound.directory "upload-envelope-$transactionId.zip";New-Item -ItemType Directory -Path $stage|Out-Null
try{$uploads=@([pscustomobject]@{path=$bound.path;name='approval.json';sha=$approvalSha},[pscustomobject]@{path=$bound.inputs.candidate.path;name='runtime.zip';sha=$bound.inputs.candidate.sha256},[pscustomobject]@{path=$bound.inputs.source_manifest.path;name='source-manifest.json';sha=$bound.inputs.source_manifest.sha256},[pscustomobject]@{path=$bound.inputs.build_result.path;name='build-result.json';sha=$bound.inputs.build_result.sha256},[pscustomobject]@{path=$bound.inputs.test_receipt.path;name='test-receipt.json';sha=$bound.inputs.test_receipt.sha256},[pscustomobject]@{path=$bound.inputs.remote_deployer.path;name=$runnerName;sha=$bound.inputs.remote_deployer.sha256});foreach($item in $uploads){$target=Join-Path $stage $item.name;Copy-Item -LiteralPath $item.path -Destination $target;if((Sha $target)-cne$item.sha){throw 'R123_STAGING_HASH_REJECTED'}};Add-Type -AssemblyName System.IO.Compression.FileSystem;[IO.Compression.ZipFile]::CreateFromDirectory($stage,$envelope,[IO.Compression.CompressionLevel]::Optimal,$false);$envelopeSha=Sha $envelope}finally{if(Test-Path -LiteralPath $stage){Remove-Item -LiteralPath $stage -Recurse -Force -ErrorAction SilentlyContinue}}
$create="if(Test-Path -LiteralPath '$remote'){throw 'R123_REMOTE_EXISTS'};New-Item -ItemType Directory -Path '$remote'|Out-Null";$create|& ssh @sshOptions $hostAlias powershell.exe -NoProfile -NonInteractive -Command -;if($LASTEXITCODE-ne0){throw 'R123_REMOTE_CREATE_FAILED'}
& scp @sshOptions $envelope "${hostAlias}:$remote\upload-envelope.zip";if($LASTEXITCODE-ne0){throw 'R123_ENVELOPE_UPLOAD_FAILED'}
$verify="function sh([string]`$p){`$s=[IO.File]::OpenRead(`$p);`$h=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString(`$h.ComputeHash(`$s))).Replace('-','').ToLowerInvariant()}finally{`$s.Dispose();`$h.Dispose()}};`$p=Join-Path '$remote' 'upload-envelope.zip';if((sh `$p)-cne'$envelopeSha'){throw 'R123_ENVELOPE_HASH_REJECTED'};if(Test-Path -LiteralPath (Join-Path '$remote' 'envelope-expanded')){throw 'R123_ENVELOPE_EXPANDED_EXISTS'};Expand-Archive -LiteralPath `$p -DestinationPath (Join-Path '$remote' 'envelope-expanded')";$verify|& ssh @sshOptions $hostAlias powershell.exe -NoProfile -NonInteractive -Command -;if($LASTEXITCODE-ne0){throw 'R123_REMOTE_VERIFY_FAILED'}
& ssh @sshOptions $hostAlias "powershell.exe -NoProfile -NonInteractive -File $remote\envelope-expanded\$runnerName -TransactionId $transactionId -RemoteRoot $remote -ApprovalSha256 $approvalSha";if($LASTEXITCODE-ne0){& scp @sshOptions "${hostAlias}:$remote\transaction-$transactionId-error.json" $errorOutput 2>$null;throw 'R123_TRANSACTION_FAILED'}
& scp @sshOptions "${hostAlias}:$remote\transaction-$transactionId-result.json" $output;if($LASTEXITCODE-ne0-or-not(Test-Path -LiteralPath $output -PathType Leaf)){throw 'R123_RESULT_DOWNLOAD_FAILED'}
$result=ReadObj $output 'R123_RESULT';if([string]$result.schema-cne'evomind.managed_hpc_identity_rebind_runtime_deployment_result.r123.v1'-or[string]$result.status-cne'installed_and_verified'-or[string]$result.transaction_id-cne$transactionId-or[string]$result.approval_sha256-cne$approvalSha-or[string]$result.web_build_id-cne$fixedWebBuild-or[string]$result.run_before.status-cne'cancelled'-or[string]$result.run_after.status-cne'cancelled'-or-not[bool]$result.run_after.terminal-or[int]$result.run_after.effective_active_count-ne0-or[int]$result.run_after.pending_approval_count-ne0-or[string]$result.installed_runtime_tree.sha256-cne$candidateTreeSha-or-not[bool]$result.run_unchanged-or-not[bool]$result.goal_unchanged-or-not[bool]$result.web_tree_unchanged-or-not[bool]$result.hpc_binding_unchanged-or-not[bool]$result.byoa_unchanged-or-not[bool]$result.profile_unchanged-or[bool]$result.hpc_accessed-or[bool]$result.gpu_touched-or[int]$result.hpc_remote_writes-ne0-or[int]$result.direct_signals_sent-ne0-or[bool]$result.other_processes_modified-or[bool]$result.training_started-or[int]$result.hpc_tool_calls-ne0){throw 'R123_RESULT_REJECTED'}
[ordered]@{status='installed_and_verified';transaction_id=$transactionId;result_path=$output;result_sha256=Sha $output;run_id=$fixedRun;target_allocation=$targetAllocation;target_job_id=$targetJob;hpc_accessed=$false;gpu_touched=$false}|ConvertTo-Json -Compress
