param([Parameter(Mandatory)][ValidatePattern('^[a-f0-9]{32}$')][string]$TransactionId,[string]$OutputPath='D:\AI-Outputs\EvoMind-Cloud-Deploy\artifacts\super-agent-v15r22-r13-hpc-executor-overlay-production-20260817.json')
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
$hostAlias='evomind-shanghai';$remote="C:\SecureInput\hpc-executor-overlay-hotfix-$TransactionId";$build='overlay-super-agent-byoa-v15r22-r9-92abb43074a5';$hotfixSha='6f4a3703c1849933520483a8320068125468928003789aa726ba6a6019a8da84';$runnerSha='d6fb027ffd45cbfc94e6f55c8c99c379dcdc9fe39fbab028c61587e5b9fd5da5';$sourceManifestSha='20d9469d66da1aa5d2ebf2d45484b5678101a77fa01e71ce341d20395a5d550b';$toolsSha='de1751cb5338e46d7baf9955af2427e3f6cdaa8e33101235372e3e6d0669c9ea';$overlaySha='6d7ba273fdbfbab37c4da48f7bb3da43bfdfffc8f41fa9117318da6631b0e44e';$hotfix='D:\AI-Outputs\EvoMind-Cloud-Deploy\artifacts\super-agent-hpc-executor-overlay-hotfix-v15r22-r13-20260817.zip';$runner=Join-Path $PSScriptRoot 'Deploy-HpcExecutorOverlayHotfixR1Remote.ps1';$output=[IO.Path]::GetFullPath($OutputPath);$errorOutput=[IO.Path]::ChangeExtension($output,'.error.json')
foreach($path in @($output,$errorOutput)){if(Test-Path -LiteralPath $path){throw "SUPER_AGENT_HPC_EXECUTOR_OVERLAY_OUTPUT_EXISTS:$path"}};foreach($item in @([pscustomobject]@{path=$hotfix;sha=$hotfixSha},[pscustomobject]@{path=$runner;sha=$runnerSha})){if(-not(Test-Path -LiteralPath $item.path -PathType Leaf)){throw "SUPER_AGENT_HPC_EXECUTOR_OVERLAY_INPUT_MISSING:$($item.path)"};if((Get-FileHash -LiteralPath $item.path -Algorithm SHA256).Hash.ToLowerInvariant()-ne$item.sha){throw "SUPER_AGENT_HPC_EXECUTOR_OVERLAY_HASH_REJECTED:$($item.path)"}}
$create="if(Test-Path -LiteralPath '$remote'){throw 'SUPER_AGENT_HPC_EXECUTOR_OVERLAY_REMOTE_EXISTS'};New-Item -ItemType Directory -Path '$remote'|Out-Null";$create|ssh $hostAlias powershell.exe -NoProfile -NonInteractive -Command -;if($LASTEXITCODE-ne0){throw 'SUPER_AGENT_HPC_EXECUTOR_OVERLAY_REMOTE_CREATE_FAILED'}
foreach($item in @([pscustomobject]@{path=$hotfix;name='hotfix.zip'},[pscustomobject]@{path=$runner;name='Deploy-HpcExecutorOverlayHotfixR1Remote.ps1'})){scp $item.path "${hostAlias}:$remote\$($item.name)";if($LASTEXITCODE-ne0){throw "SUPER_AGENT_HPC_EXECUTOR_OVERLAY_UPLOAD_FAILED:$($item.name)"}}
$verify="`$files=@([pscustomobject]@{name='hotfix.zip';sha='$hotfixSha'},[pscustomobject]@{name='Deploy-HpcExecutorOverlayHotfixR1Remote.ps1';sha='$runnerSha'});foreach(`$i in `$files){`$p=Join-Path '$remote' `$i.name;if((Get-FileHash -LiteralPath `$p -Algorithm SHA256).Hash.ToLowerInvariant()-ne`$i.sha){throw 'SUPER_AGENT_HPC_EXECUTOR_OVERLAY_REMOTE_HASH_REJECTED'}};`$tokens=`$null;`$errors=`$null;[Management.Automation.Language.Parser]::ParseFile((Join-Path '$remote' 'Deploy-HpcExecutorOverlayHotfixR1Remote.ps1'),[ref]`$tokens,[ref]`$errors)|Out-Null;if(@(`$errors).Count){throw 'SUPER_AGENT_HPC_EXECUTOR_OVERLAY_REMOTE_AST_REJECTED'};[ordered]@{status='staged_verified';transaction_id='$TransactionId'}|ConvertTo-Json -Compress";$staged=$verify|ssh $hostAlias powershell.exe -NoProfile -NonInteractive -Command -;if($LASTEXITCODE-ne0){throw 'SUPER_AGENT_HPC_EXECUTOR_OVERLAY_REMOTE_VERIFY_FAILED'};$staged
ssh $hostAlias "powershell.exe -NoProfile -NonInteractive -File $remote\Deploy-HpcExecutorOverlayHotfixR1Remote.ps1 -TransactionId $TransactionId -RemoteRoot $remote -HotfixSha256 $hotfixSha -ExpectedBuildId $build";if($LASTEXITCODE-ne0){scp "${hostAlias}:$remote\transaction-$TransactionId-error.json" $errorOutput 2>$null;throw 'SUPER_AGENT_HPC_EXECUTOR_OVERLAY_TRANSACTION_FAILED'};scp "${hostAlias}:$remote\transaction-$TransactionId-result.json" $output;if($LASTEXITCODE-ne0-or-not(Test-Path -LiteralPath $output -PathType Leaf)){throw 'SUPER_AGENT_HPC_EXECUTOR_OVERLAY_RESULT_DOWNLOAD_FAILED'}
$r=Get-Content -LiteralPath $output -Raw -Encoding UTF8|ConvertFrom-Json;if([string]$r.status-ne'installed_and_verified'-or[string]$r.transaction_id-ne$TransactionId-or[string]$r.build_id-ne$build-or[string]$r.hotfix_sha256-ne$hotfixSha-or[string]$r.source_manifest_sha256-ne$sourceManifestSha-or[string]$r.tools_sha256-ne$toolsSha-or[string]$r.overlay_sha256-ne$overlaySha-or[int]$r.updated_target_count-ne2-or-not[bool]$r.hpc_binding_unchanged-or-not[bool]$r.byoa_tree_unchanged-or-not[bool]$r.profile_unchanged-or[int]$r.job_id-ne91699-or[int]$r.allocation_generation-ne15-or[string]$r.binding_state-ne'active'-or[bool]$r.hpc_accessed-or[bool]$r.gpu_touched-or[bool]$r.training_started-or[int]$r.kaggle_submissions-ne0){throw 'SUPER_AGENT_HPC_EXECUTOR_OVERLAY_RESULT_REJECTED'};[ordered]@{status='installed_and_verified';transaction_id=$TransactionId;build_id=$build;result_path=$output;result_sha256=(Get-FileHash -LiteralPath $output -Algorithm SHA256).Hash.ToLowerInvariant()}|ConvertTo-Json -Compress
