"""Leakage-free meta-model utilities for Spooky Author Identification.

The module deliberately has no knowledge of private labels or official grader
results.  Each held outer fold is scored by a meta-model fitted only on OOF
rows from the other folds.  The corresponding fold-trained base test features
are transformed by that same meta-model before foldwise test averaging.
"""

from __future__ import annotations

import hashlib
import math
from collections.abc import Mapping
from typing import Any

import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler


def normalize_probability(values: np.ndarray) -> np.ndarray:
    """Return finite row-normalized probabilities with a stable floor."""

    result = np.asarray(values, dtype=np.float64)
    if result.ndim != 2 or result.shape[1] < 2:
        raise ValueError("Probability matrices must be two-dimensional with at least two classes")
    if not np.isfinite(result).all():
        raise ValueError("Probability matrices must be finite")
    result = np.clip(result, 1e-7, None)
    row_sum = result.sum(axis=1, keepdims=True)
    if np.any(row_sum <= 0.0):
        raise ValueError("Probability rows must have positive mass")
    return result / row_sum


def _validate_dense_feature_matrix(values: np.ndarray, *, rows: int, name: str) -> np.ndarray:
    matrix = np.asarray(values, dtype=np.float64)
    if matrix.ndim != 2 or matrix.shape[0] != rows or matrix.shape[1] < 1:
        raise ValueError(f"{name} has an invalid shape")
    if not np.isfinite(matrix).all():
        raise ValueError(f"{name} includes non-finite values")
    return matrix


def assemble_meta_features(
    probability_channels: Mapping[str, np.ndarray],
    *,
    style_features: np.ndarray | None = None,
    embedding_features: np.ndarray | None = None,
) -> tuple[np.ndarray, dict[str, Any]]:
    """Assemble named probability, style, and embedding channels.

    Probability channels are normalized before concatenation.  The returned
    contract records exact column ranges, making train/test construction and
    independent reconstruction auditable.
    """

    if not probability_channels:
        raise ValueError("At least one probability channel is required")
    names = tuple(probability_channels)
    first = np.asarray(probability_channels[names[0]])
    if first.ndim != 2:
        raise ValueError("Probability channels must be matrices")
    rows = first.shape[0]
    blocks: list[np.ndarray] = []
    columns: list[dict[str, Any]] = []
    offset = 0
    for name, values in probability_channels.items():
        matrix = normalize_probability(values)
        if matrix.shape[0] != rows:
            raise ValueError("Probability channels are not row-aligned")
        blocks.append(matrix)
        columns.append(
            {
                "name": name,
                "kind": "probability",
                "start": offset,
                "stop": offset + matrix.shape[1],
            }
        )
        offset += matrix.shape[1]
    for name, values in (
        ("style", style_features),
        ("embedding", embedding_features),
    ):
        if values is None:
            continue
        matrix = _validate_dense_feature_matrix(values, rows=rows, name=name)
        blocks.append(matrix)
        columns.append(
            {
                "name": name,
                "kind": "dense",
                "start": offset,
                "stop": offset + matrix.shape[1],
            }
        )
        offset += matrix.shape[1]
    result = np.concatenate(blocks, axis=1)
    return result, {
        "schema": "evomind.spooky.meta_feature_contract.v1",
        "rows": rows,
        "columns": result.shape[1],
        "blocks": columns,
        "private_labels_used": False,
    }


def _index_sha256(indices: np.ndarray) -> str:
    contiguous = np.ascontiguousarray(np.asarray(indices, dtype=np.int64))
    return hashlib.sha256(contiguous.tobytes()).hexdigest()


def cross_fit_logistic_meta(
    oof_features: np.ndarray,
    test_features_by_fold: np.ndarray,
    truth: np.ndarray,
    fold_assignment: np.ndarray,
    *,
    c_value: float = 1.0,
    max_iter: int = 2000,
    random_state: int = 42,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, dict[str, Any]]:
    """Cross-fit a regularized multinomial logistic meta-model.

    For score fold ``f`` the scaler and classifier are fitted on rows whose
    outer fold is not ``f``.  They then score only fold ``f`` and the base test
    features generated by base model ``f``.  Averaging the foldwise test
    probabilities mirrors the OOF topology and prevents the meta-model from
    observing the labels of the rows it scores.
    """

    if not math.isfinite(c_value) or c_value <= 0.0:
        raise ValueError("c_value must be finite and positive")
    features = np.asarray(oof_features, dtype=np.float64)
    labels = np.asarray(truth, dtype=np.int64).reshape(-1)
    folds = np.asarray(fold_assignment, dtype=np.int16).reshape(-1)
    if features.ndim != 2 or len(features) != len(labels) or len(labels) != len(folds):
        raise ValueError("OOF features, truth, and folds are not row-aligned")
    if not np.isfinite(features).all():
        raise ValueError("OOF features include non-finite values")
    unique_folds = sorted(int(value) for value in np.unique(folds))
    if unique_folds != list(range(len(unique_folds))) or len(unique_folds) < 3:
        raise ValueError("Outer folds must be contiguous, zero-based, and include at least three folds")
    class_count = int(labels.max(initial=-1)) + 1
    if class_count < 2 or not np.array_equal(np.unique(labels), np.arange(class_count)):
        raise ValueError("Truth labels must be contiguous and zero-based")
    test_features = np.asarray(test_features_by_fold, dtype=np.float64)
    if test_features.ndim != 3:
        raise ValueError("Test meta-features require one aligned matrix per outer fold")
    expected_test_shape = (len(unique_folds), test_features.shape[1], features.shape[1])
    if test_features.shape != expected_test_shape:
        raise ValueError("Test meta-features require one aligned matrix per outer fold")
    if not np.isfinite(test_features).all():
        raise ValueError("Test meta-features include non-finite values")

    candidate_oof = np.full((len(labels), class_count), np.nan, dtype=np.float64)
    candidate_counts = np.zeros(len(labels), dtype=np.uint8)
    foldwise_test = np.zeros((len(unique_folds), test_features.shape[1], class_count))
    records: list[dict[str, Any]] = []
    for fold in unique_folds:
        fit_indices = np.flatnonzero(folds != fold)
        score_indices = np.flatnonzero(folds == fold)
        if np.intersect1d(fit_indices, score_indices).size:
            raise RuntimeError("Meta fit and score rows overlap")
        scaler = StandardScaler()
        fit_scaled = scaler.fit_transform(features[fit_indices])
        score_scaled = scaler.transform(features[score_indices])
        test_scaled = scaler.transform(test_features[fold])
        model = LogisticRegression(
            C=c_value,
            max_iter=max_iter,
            solver="lbfgs",
            random_state=random_state + fold,
        )
        model.fit(fit_scaled, labels[fit_indices])
        if not np.array_equal(model.classes_, np.arange(class_count)):
            raise RuntimeError("Meta classifier class order changed")
        candidate_oof[score_indices] = normalize_probability(model.predict_proba(score_scaled))
        candidate_counts[score_indices] += 1
        foldwise_test[fold] = normalize_probability(model.predict_proba(test_scaled))
        records.append(
            {
                "score_fold": fold,
                "fit_folds": [value for value in unique_folds if value != fold],
                "fit_rows": len(fit_indices),
                "score_rows": len(score_indices),
                "fit_index_sha256": _index_sha256(fit_indices),
                "score_index_sha256": _index_sha256(score_indices),
                "fit_score_disjoint": True,
                "iterations": int(np.max(model.n_iter_)),
            }
        )
    if not np.all(candidate_counts == 1) or not np.isfinite(candidate_oof).all():
        raise RuntimeError("Meta OOF predictions were not written exactly once")
    candidate_test = normalize_probability(foldwise_test.mean(axis=0))
    contract = {
        "schema": "evomind.spooky.leakage_free_logistic_meta.v1",
        "outer_folds": unique_folds,
        "selection": "fit_other_oof_folds_score_held_outer_fold",
        "test_aggregation": "apply_corresponding_fold_meta_then_average",
        "c_value": c_value,
        "max_iter": max_iter,
        "feature_count": features.shape[1],
        "records": records,
        "exact_once_oof": True,
        "private_labels_used": False,
        "official_grader_executed": False,
        "kaggle_submission_executed": False,
    }
    return candidate_oof, candidate_test, candidate_counts, contract
